//File Automatically generated by SystemC Netlister Time
#ifndef BD_28BA_H
#define BD_28BA_H
#include "systemc.h"
#include "xtlm.h"
#include "bd_28ba_MC1_ddrc_0.h"
#include "bd_28ba_MC0_ddrc_0.h"
#include "bd_28ba_sci.h"

class bd_28ba : public bd_28ba_sci {

public:
	
	//Port declaration
	sc_out< sc_bv<6> > CH0_LPDDR4_0_ca_a;
	sc_out< sc_bv<6> > CH0_LPDDR4_0_ca_b;
	sc_out< sc_bv<1> > CH0_LPDDR4_0_ck_c_a;
	sc_out< sc_bv<1> > CH0_LPDDR4_0_ck_c_b;
	sc_out< sc_bv<1> > CH0_LPDDR4_0_ck_t_a;
	sc_out< sc_bv<1> > CH0_LPDDR4_0_ck_t_b;
	sc_out< sc_bv<1> > CH0_LPDDR4_0_cke_a;
	sc_out< sc_bv<1> > CH0_LPDDR4_0_cke_b;
	sc_out< sc_bv<1> > CH0_LPDDR4_0_cs_a;
	sc_out< sc_bv<1> > CH0_LPDDR4_0_cs_b;
	sc_inout< sc_bv<2> > CH0_LPDDR4_0_dmi_a;
	sc_inout< sc_bv<2> > CH0_LPDDR4_0_dmi_b;
	sc_inout< sc_bv<16> > CH0_LPDDR4_0_dq_a;
	sc_inout< sc_bv<16> > CH0_LPDDR4_0_dq_b;
	sc_inout< sc_bv<2> > CH0_LPDDR4_0_dqs_c_a;
	sc_inout< sc_bv<2> > CH0_LPDDR4_0_dqs_c_b;
	sc_inout< sc_bv<2> > CH0_LPDDR4_0_dqs_t_a;
	sc_inout< sc_bv<2> > CH0_LPDDR4_0_dqs_t_b;
	sc_out< sc_bv<1> > CH0_LPDDR4_0_reset_n;
	sc_out< sc_bv<6> > CH0_LPDDR4_1_ca_a;
	sc_out< sc_bv<6> > CH0_LPDDR4_1_ca_b;
	sc_out< sc_bv<1> > CH0_LPDDR4_1_ck_c_a;
	sc_out< sc_bv<1> > CH0_LPDDR4_1_ck_c_b;
	sc_out< sc_bv<1> > CH0_LPDDR4_1_ck_t_a;
	sc_out< sc_bv<1> > CH0_LPDDR4_1_ck_t_b;
	sc_out< sc_bv<1> > CH0_LPDDR4_1_cke_a;
	sc_out< sc_bv<1> > CH0_LPDDR4_1_cke_b;
	sc_out< sc_bv<1> > CH0_LPDDR4_1_cs_a;
	sc_out< sc_bv<1> > CH0_LPDDR4_1_cs_b;
	sc_inout< sc_bv<2> > CH0_LPDDR4_1_dmi_a;
	sc_inout< sc_bv<2> > CH0_LPDDR4_1_dmi_b;
	sc_inout< sc_bv<16> > CH0_LPDDR4_1_dq_a;
	sc_inout< sc_bv<16> > CH0_LPDDR4_1_dq_b;
	sc_inout< sc_bv<2> > CH0_LPDDR4_1_dqs_c_a;
	sc_inout< sc_bv<2> > CH0_LPDDR4_1_dqs_c_b;
	sc_inout< sc_bv<2> > CH0_LPDDR4_1_dqs_t_a;
	sc_inout< sc_bv<2> > CH0_LPDDR4_1_dqs_t_b;
	sc_out< sc_bv<1> > CH0_LPDDR4_1_reset_n;
	sc_out< sc_bv<6> > CH1_LPDDR4_0_ca_a;
	sc_out< sc_bv<6> > CH1_LPDDR4_0_ca_b;
	sc_out< sc_bv<1> > CH1_LPDDR4_0_ck_c_a;
	sc_out< sc_bv<1> > CH1_LPDDR4_0_ck_c_b;
	sc_out< sc_bv<1> > CH1_LPDDR4_0_ck_t_a;
	sc_out< sc_bv<1> > CH1_LPDDR4_0_ck_t_b;
	sc_out< sc_bv<1> > CH1_LPDDR4_0_cke_a;
	sc_out< sc_bv<1> > CH1_LPDDR4_0_cke_b;
	sc_out< sc_bv<1> > CH1_LPDDR4_0_cs_a;
	sc_out< sc_bv<1> > CH1_LPDDR4_0_cs_b;
	sc_inout< sc_bv<2> > CH1_LPDDR4_0_dmi_a;
	sc_inout< sc_bv<2> > CH1_LPDDR4_0_dmi_b;
	sc_inout< sc_bv<16> > CH1_LPDDR4_0_dq_a;
	sc_inout< sc_bv<16> > CH1_LPDDR4_0_dq_b;
	sc_inout< sc_bv<2> > CH1_LPDDR4_0_dqs_c_a;
	sc_inout< sc_bv<2> > CH1_LPDDR4_0_dqs_c_b;
	sc_inout< sc_bv<2> > CH1_LPDDR4_0_dqs_t_a;
	sc_inout< sc_bv<2> > CH1_LPDDR4_0_dqs_t_b;
	sc_out< sc_bv<1> > CH1_LPDDR4_0_reset_n;
	sc_out< sc_bv<6> > CH1_LPDDR4_1_ca_a;
	sc_out< sc_bv<6> > CH1_LPDDR4_1_ca_b;
	sc_out< sc_bv<1> > CH1_LPDDR4_1_ck_c_a;
	sc_out< sc_bv<1> > CH1_LPDDR4_1_ck_c_b;
	sc_out< sc_bv<1> > CH1_LPDDR4_1_ck_t_a;
	sc_out< sc_bv<1> > CH1_LPDDR4_1_ck_t_b;
	sc_out< sc_bv<1> > CH1_LPDDR4_1_cke_a;
	sc_out< sc_bv<1> > CH1_LPDDR4_1_cke_b;
	sc_out< sc_bv<1> > CH1_LPDDR4_1_cs_a;
	sc_out< sc_bv<1> > CH1_LPDDR4_1_cs_b;
	sc_inout< sc_bv<2> > CH1_LPDDR4_1_dmi_a;
	sc_inout< sc_bv<2> > CH1_LPDDR4_1_dmi_b;
	sc_inout< sc_bv<16> > CH1_LPDDR4_1_dq_a;
	sc_inout< sc_bv<16> > CH1_LPDDR4_1_dq_b;
	sc_inout< sc_bv<2> > CH1_LPDDR4_1_dqs_c_a;
	sc_inout< sc_bv<2> > CH1_LPDDR4_1_dqs_c_b;
	sc_inout< sc_bv<2> > CH1_LPDDR4_1_dqs_t_a;
	sc_inout< sc_bv<2> > CH1_LPDDR4_1_dqs_t_b;
	sc_out< sc_bv<1> > CH1_LPDDR4_1_reset_n;
	sc_in< sc_bv<1> > S00_INI_internoc;
	sc_in< sc_bv<1> > S01_INI_internoc;
	sc_in< sc_bv<1> > S02_INI_internoc;
	sc_in< sc_bv<1> > S03_INI_internoc;
	sc_in< sc_bv<1> > sys_clk0_clk_n;
	sc_in< sc_bv<1> > sys_clk0_clk_p;
	sc_in< sc_bv<1> > sys_clk1_clk_n;
	sc_in< sc_bv<1> > sys_clk1_clk_p;
	
	//Instance declaration
	bd_28ba_MC0_ddrc_0* MC0_ddrc;
	bd_28ba_MC1_ddrc_0* MC1_ddrc;
	
	//Signal Declaration
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_0_driver_signal;
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_1_driver_signal;
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_2_driver_signal;
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_3_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_0_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_1_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_2_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_3_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_0_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_1_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_2_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_3_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_0_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_1_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_2_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_3_driver_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_0_stub_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_1_stub_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_2_stub_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_3_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_0_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_1_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_2_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_3_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_0_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_1_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_2_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_3_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_0_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_1_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_2_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_3_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_0_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_1_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_2_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_3_stub_signal;
	sc_signal<bool>     MC0_ddrc_sys_clk_n_connect_signal;
	sc_signal<bool>     MC0_ddrc_sys_clk_p_connect_signal;
	sc_signal<bool>     MC1_ddrc_dmc2noc_credit_rdy_0_driver_signal;
	sc_signal<bool>     MC1_ddrc_dmc2noc_credit_rdy_1_driver_signal;
	sc_signal<bool>     MC1_ddrc_dmc2noc_credit_rdy_2_driver_signal;
	sc_signal<bool>     MC1_ddrc_dmc2noc_credit_rdy_3_driver_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_dmc2noc_credit_rtn_0_driver_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_dmc2noc_credit_rtn_1_driver_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_dmc2noc_credit_rtn_2_driver_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_dmc2noc_credit_rtn_3_driver_signal;
	sc_signal< sc_bv<182> > MC1_ddrc_dmc2noc_data_out_0_driver_signal;
	sc_signal< sc_bv<182> > MC1_ddrc_dmc2noc_data_out_1_driver_signal;
	sc_signal< sc_bv<182> > MC1_ddrc_dmc2noc_data_out_2_driver_signal;
	sc_signal< sc_bv<182> > MC1_ddrc_dmc2noc_data_out_3_driver_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_dmc2noc_valid_out_0_driver_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_dmc2noc_valid_out_1_driver_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_dmc2noc_valid_out_2_driver_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_dmc2noc_valid_out_3_driver_signal;
	sc_signal<bool>     MC1_ddrc_from_noc_0_stub_signal;
	sc_signal<bool>     MC1_ddrc_from_noc_1_stub_signal;
	sc_signal<bool>     MC1_ddrc_from_noc_2_stub_signal;
	sc_signal<bool>     MC1_ddrc_from_noc_3_stub_signal;
	sc_signal<bool>     MC1_ddrc_noc2dmc_credit_rdy_0_stub_signal;
	sc_signal<bool>     MC1_ddrc_noc2dmc_credit_rdy_1_stub_signal;
	sc_signal<bool>     MC1_ddrc_noc2dmc_credit_rdy_2_stub_signal;
	sc_signal<bool>     MC1_ddrc_noc2dmc_credit_rdy_3_stub_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_noc2dmc_credit_rtn_0_stub_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_noc2dmc_credit_rtn_1_stub_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_noc2dmc_credit_rtn_2_stub_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_noc2dmc_credit_rtn_3_stub_signal;
	sc_signal< sc_bv<182> > MC1_ddrc_noc2dmc_data_in_0_stub_signal;
	sc_signal< sc_bv<182> > MC1_ddrc_noc2dmc_data_in_1_stub_signal;
	sc_signal< sc_bv<182> > MC1_ddrc_noc2dmc_data_in_2_stub_signal;
	sc_signal< sc_bv<182> > MC1_ddrc_noc2dmc_data_in_3_stub_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_noc2dmc_valid_in_0_stub_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_noc2dmc_valid_in_1_stub_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_noc2dmc_valid_in_2_stub_signal;
	sc_signal< sc_bv<8> > MC1_ddrc_noc2dmc_valid_in_3_stub_signal;
	sc_signal<bool>     MC1_ddrc_sys_clk_n_connect_signal;
	sc_signal<bool>     MC1_ddrc_sys_clk_p_connect_signal;
	
	
	//Thread Methods
	void MC0_ddrc_sys_clk_n_DRIVER_METHOD();
	void MC0_ddrc_sys_clk_p_DRIVER_METHOD();
	void MC1_ddrc_sys_clk_n_DRIVER_METHOD();
	void MC1_ddrc_sys_clk_p_DRIVER_METHOD();
	
	//Constructor for the module
	bd_28ba(const sc_module_name& module_name,xsc::common_cpp::properties& properties);
	SC_HAS_PROCESS(bd_28ba);
	//Destructor for the module
	~bd_28ba();
	

protected:

private:
	bd_28ba(const bd_28ba&);
	const bd_28ba& operator=(const bd_28ba&);
};
#endif
