//File Automatically generated by SystemC Netlister Time
#include "bd_28ba.h"
bd_28ba::bd_28ba(const sc_module_name& module_name,xsc::common_cpp::properties& properties) : bd_28ba_sci(module_name) 
,CH0_LPDDR4_0_ca_a("CH0_LPDDR4_0_ca_a")
,CH0_LPDDR4_0_ca_b("CH0_LPDDR4_0_ca_b")
,CH0_LPDDR4_0_ck_c_a("CH0_LPDDR4_0_ck_c_a")
,CH0_LPDDR4_0_ck_c_b("CH0_LPDDR4_0_ck_c_b")
,CH0_LPDDR4_0_ck_t_a("CH0_LPDDR4_0_ck_t_a")
,CH0_LPDDR4_0_ck_t_b("CH0_LPDDR4_0_ck_t_b")
,CH0_LPDDR4_0_cke_a("CH0_LPDDR4_0_cke_a")
,CH0_LPDDR4_0_cke_b("CH0_LPDDR4_0_cke_b")
,CH0_LPDDR4_0_cs_a("CH0_LPDDR4_0_cs_a")
,CH0_LPDDR4_0_cs_b("CH0_LPDDR4_0_cs_b")
,CH0_LPDDR4_0_dmi_a("CH0_LPDDR4_0_dmi_a")
,CH0_LPDDR4_0_dmi_b("CH0_LPDDR4_0_dmi_b")
,CH0_LPDDR4_0_dq_a("CH0_LPDDR4_0_dq_a")
,CH0_LPDDR4_0_dq_b("CH0_LPDDR4_0_dq_b")
,CH0_LPDDR4_0_dqs_c_a("CH0_LPDDR4_0_dqs_c_a")
,CH0_LPDDR4_0_dqs_c_b("CH0_LPDDR4_0_dqs_c_b")
,CH0_LPDDR4_0_dqs_t_a("CH0_LPDDR4_0_dqs_t_a")
,CH0_LPDDR4_0_dqs_t_b("CH0_LPDDR4_0_dqs_t_b")
,CH0_LPDDR4_0_reset_n("CH0_LPDDR4_0_reset_n")
,CH0_LPDDR4_1_ca_a("CH0_LPDDR4_1_ca_a")
,CH0_LPDDR4_1_ca_b("CH0_LPDDR4_1_ca_b")
,CH0_LPDDR4_1_ck_c_a("CH0_LPDDR4_1_ck_c_a")
,CH0_LPDDR4_1_ck_c_b("CH0_LPDDR4_1_ck_c_b")
,CH0_LPDDR4_1_ck_t_a("CH0_LPDDR4_1_ck_t_a")
,CH0_LPDDR4_1_ck_t_b("CH0_LPDDR4_1_ck_t_b")
,CH0_LPDDR4_1_cke_a("CH0_LPDDR4_1_cke_a")
,CH0_LPDDR4_1_cke_b("CH0_LPDDR4_1_cke_b")
,CH0_LPDDR4_1_cs_a("CH0_LPDDR4_1_cs_a")
,CH0_LPDDR4_1_cs_b("CH0_LPDDR4_1_cs_b")
,CH0_LPDDR4_1_dmi_a("CH0_LPDDR4_1_dmi_a")
,CH0_LPDDR4_1_dmi_b("CH0_LPDDR4_1_dmi_b")
,CH0_LPDDR4_1_dq_a("CH0_LPDDR4_1_dq_a")
,CH0_LPDDR4_1_dq_b("CH0_LPDDR4_1_dq_b")
,CH0_LPDDR4_1_dqs_c_a("CH0_LPDDR4_1_dqs_c_a")
,CH0_LPDDR4_1_dqs_c_b("CH0_LPDDR4_1_dqs_c_b")
,CH0_LPDDR4_1_dqs_t_a("CH0_LPDDR4_1_dqs_t_a")
,CH0_LPDDR4_1_dqs_t_b("CH0_LPDDR4_1_dqs_t_b")
,CH0_LPDDR4_1_reset_n("CH0_LPDDR4_1_reset_n")
,CH1_LPDDR4_0_ca_a("CH1_LPDDR4_0_ca_a")
,CH1_LPDDR4_0_ca_b("CH1_LPDDR4_0_ca_b")
,CH1_LPDDR4_0_ck_c_a("CH1_LPDDR4_0_ck_c_a")
,CH1_LPDDR4_0_ck_c_b("CH1_LPDDR4_0_ck_c_b")
,CH1_LPDDR4_0_ck_t_a("CH1_LPDDR4_0_ck_t_a")
,CH1_LPDDR4_0_ck_t_b("CH1_LPDDR4_0_ck_t_b")
,CH1_LPDDR4_0_cke_a("CH1_LPDDR4_0_cke_a")
,CH1_LPDDR4_0_cke_b("CH1_LPDDR4_0_cke_b")
,CH1_LPDDR4_0_cs_a("CH1_LPDDR4_0_cs_a")
,CH1_LPDDR4_0_cs_b("CH1_LPDDR4_0_cs_b")
,CH1_LPDDR4_0_dmi_a("CH1_LPDDR4_0_dmi_a")
,CH1_LPDDR4_0_dmi_b("CH1_LPDDR4_0_dmi_b")
,CH1_LPDDR4_0_dq_a("CH1_LPDDR4_0_dq_a")
,CH1_LPDDR4_0_dq_b("CH1_LPDDR4_0_dq_b")
,CH1_LPDDR4_0_dqs_c_a("CH1_LPDDR4_0_dqs_c_a")
,CH1_LPDDR4_0_dqs_c_b("CH1_LPDDR4_0_dqs_c_b")
,CH1_LPDDR4_0_dqs_t_a("CH1_LPDDR4_0_dqs_t_a")
,CH1_LPDDR4_0_dqs_t_b("CH1_LPDDR4_0_dqs_t_b")
,CH1_LPDDR4_0_reset_n("CH1_LPDDR4_0_reset_n")
,CH1_LPDDR4_1_ca_a("CH1_LPDDR4_1_ca_a")
,CH1_LPDDR4_1_ca_b("CH1_LPDDR4_1_ca_b")
,CH1_LPDDR4_1_ck_c_a("CH1_LPDDR4_1_ck_c_a")
,CH1_LPDDR4_1_ck_c_b("CH1_LPDDR4_1_ck_c_b")
,CH1_LPDDR4_1_ck_t_a("CH1_LPDDR4_1_ck_t_a")
,CH1_LPDDR4_1_ck_t_b("CH1_LPDDR4_1_ck_t_b")
,CH1_LPDDR4_1_cke_a("CH1_LPDDR4_1_cke_a")
,CH1_LPDDR4_1_cke_b("CH1_LPDDR4_1_cke_b")
,CH1_LPDDR4_1_cs_a("CH1_LPDDR4_1_cs_a")
,CH1_LPDDR4_1_cs_b("CH1_LPDDR4_1_cs_b")
,CH1_LPDDR4_1_dmi_a("CH1_LPDDR4_1_dmi_a")
,CH1_LPDDR4_1_dmi_b("CH1_LPDDR4_1_dmi_b")
,CH1_LPDDR4_1_dq_a("CH1_LPDDR4_1_dq_a")
,CH1_LPDDR4_1_dq_b("CH1_LPDDR4_1_dq_b")
,CH1_LPDDR4_1_dqs_c_a("CH1_LPDDR4_1_dqs_c_a")
,CH1_LPDDR4_1_dqs_c_b("CH1_LPDDR4_1_dqs_c_b")
,CH1_LPDDR4_1_dqs_t_a("CH1_LPDDR4_1_dqs_t_a")
,CH1_LPDDR4_1_dqs_t_b("CH1_LPDDR4_1_dqs_t_b")
,CH1_LPDDR4_1_reset_n("CH1_LPDDR4_1_reset_n")
,S00_INI_internoc("S00_INI_internoc")
,S01_INI_internoc("S01_INI_internoc")
,S02_INI_internoc("S02_INI_internoc")
,S03_INI_internoc("S03_INI_internoc")
,sys_clk0_clk_n("sys_clk0_clk_n")
,sys_clk0_clk_p("sys_clk0_clk_p")
,sys_clk1_clk_n("sys_clk1_clk_n")
,sys_clk1_clk_p("sys_clk1_clk_p")
{
	//Instance Instantiation
	MC0_ddrc=new bd_28ba_MC0_ddrc_0("MC0_ddrc");
	MC1_ddrc=new bd_28ba_MC1_ddrc_0("MC1_ddrc");
	
	//Signal Connections
	MC0_ddrc->ch0_lpddr4_dmi_a(CH0_LPDDR4_0_dmi_a);
	MC0_ddrc->ch0_lpddr4_dmi_b(CH0_LPDDR4_0_dmi_b);
	MC0_ddrc->ch0_lpddr4_dq_a(CH0_LPDDR4_0_dq_a);
	MC0_ddrc->ch0_lpddr4_dq_b(CH0_LPDDR4_0_dq_b);
	MC0_ddrc->ch0_lpddr4_dqs_c_a(CH0_LPDDR4_0_dqs_c_a);
	MC0_ddrc->ch0_lpddr4_dqs_c_b(CH0_LPDDR4_0_dqs_c_b);
	MC0_ddrc->ch0_lpddr4_dqs_t_a(CH0_LPDDR4_0_dqs_t_a);
	MC0_ddrc->ch0_lpddr4_dqs_t_b(CH0_LPDDR4_0_dqs_t_b);
	MC0_ddrc->ch1_lpddr4_dmi_a(CH1_LPDDR4_0_dmi_a);
	MC0_ddrc->ch1_lpddr4_dmi_b(CH1_LPDDR4_0_dmi_b);
	MC0_ddrc->ch1_lpddr4_dq_a(CH1_LPDDR4_0_dq_a);
	MC0_ddrc->ch1_lpddr4_dq_b(CH1_LPDDR4_0_dq_b);
	MC0_ddrc->ch1_lpddr4_dqs_c_a(CH1_LPDDR4_0_dqs_c_a);
	MC0_ddrc->ch1_lpddr4_dqs_c_b(CH1_LPDDR4_0_dqs_c_b);
	MC0_ddrc->ch1_lpddr4_dqs_t_a(CH1_LPDDR4_0_dqs_t_a);
	MC0_ddrc->ch1_lpddr4_dqs_t_b(CH1_LPDDR4_0_dqs_t_b);
	MC0_ddrc->dmc2noc_credit_rdy_0(MC0_ddrc_dmc2noc_credit_rdy_0_driver_signal);
	MC0_ddrc->dmc2noc_credit_rdy_1(MC0_ddrc_dmc2noc_credit_rdy_1_driver_signal);
	MC0_ddrc->dmc2noc_credit_rdy_2(MC0_ddrc_dmc2noc_credit_rdy_2_driver_signal);
	MC0_ddrc->dmc2noc_credit_rdy_3(MC0_ddrc_dmc2noc_credit_rdy_3_driver_signal);
	MC0_ddrc->dmc2noc_credit_rtn_0(MC0_ddrc_dmc2noc_credit_rtn_0_driver_signal);
	MC0_ddrc->dmc2noc_credit_rtn_1(MC0_ddrc_dmc2noc_credit_rtn_1_driver_signal);
	MC0_ddrc->dmc2noc_credit_rtn_2(MC0_ddrc_dmc2noc_credit_rtn_2_driver_signal);
	MC0_ddrc->dmc2noc_credit_rtn_3(MC0_ddrc_dmc2noc_credit_rtn_3_driver_signal);
	MC0_ddrc->dmc2noc_data_out_0(MC0_ddrc_dmc2noc_data_out_0_driver_signal);
	MC0_ddrc->dmc2noc_data_out_1(MC0_ddrc_dmc2noc_data_out_1_driver_signal);
	MC0_ddrc->dmc2noc_data_out_2(MC0_ddrc_dmc2noc_data_out_2_driver_signal);
	MC0_ddrc->dmc2noc_data_out_3(MC0_ddrc_dmc2noc_data_out_3_driver_signal);
	MC0_ddrc->dmc2noc_valid_out_0(MC0_ddrc_dmc2noc_valid_out_0_driver_signal);
	MC0_ddrc->dmc2noc_valid_out_1(MC0_ddrc_dmc2noc_valid_out_1_driver_signal);
	MC0_ddrc->dmc2noc_valid_out_2(MC0_ddrc_dmc2noc_valid_out_2_driver_signal);
	MC0_ddrc->dmc2noc_valid_out_3(MC0_ddrc_dmc2noc_valid_out_3_driver_signal);
	MC0_ddrc->from_noc_0(MC0_ddrc_from_noc_0_stub_signal);
	MC0_ddrc->from_noc_1(MC0_ddrc_from_noc_1_stub_signal);
	MC0_ddrc->from_noc_2(MC0_ddrc_from_noc_2_stub_signal);
	MC0_ddrc->from_noc_3(MC0_ddrc_from_noc_3_stub_signal);
	MC0_ddrc->noc2dmc_credit_rdy_0(MC0_ddrc_noc2dmc_credit_rdy_0_stub_signal);
	MC0_ddrc->noc2dmc_credit_rdy_1(MC0_ddrc_noc2dmc_credit_rdy_1_stub_signal);
	MC0_ddrc->noc2dmc_credit_rdy_2(MC0_ddrc_noc2dmc_credit_rdy_2_stub_signal);
	MC0_ddrc->noc2dmc_credit_rdy_3(MC0_ddrc_noc2dmc_credit_rdy_3_stub_signal);
	MC0_ddrc->noc2dmc_credit_rtn_0(MC0_ddrc_noc2dmc_credit_rtn_0_stub_signal);
	MC0_ddrc->noc2dmc_credit_rtn_1(MC0_ddrc_noc2dmc_credit_rtn_1_stub_signal);
	MC0_ddrc->noc2dmc_credit_rtn_2(MC0_ddrc_noc2dmc_credit_rtn_2_stub_signal);
	MC0_ddrc->noc2dmc_credit_rtn_3(MC0_ddrc_noc2dmc_credit_rtn_3_stub_signal);
	MC0_ddrc->noc2dmc_data_in_0(MC0_ddrc_noc2dmc_data_in_0_stub_signal);
	MC0_ddrc->noc2dmc_data_in_1(MC0_ddrc_noc2dmc_data_in_1_stub_signal);
	MC0_ddrc->noc2dmc_data_in_2(MC0_ddrc_noc2dmc_data_in_2_stub_signal);
	MC0_ddrc->noc2dmc_data_in_3(MC0_ddrc_noc2dmc_data_in_3_stub_signal);
	MC0_ddrc->noc2dmc_valid_in_0(MC0_ddrc_noc2dmc_valid_in_0_stub_signal);
	MC0_ddrc->noc2dmc_valid_in_1(MC0_ddrc_noc2dmc_valid_in_1_stub_signal);
	MC0_ddrc->noc2dmc_valid_in_2(MC0_ddrc_noc2dmc_valid_in_2_stub_signal);
	MC0_ddrc->noc2dmc_valid_in_3(MC0_ddrc_noc2dmc_valid_in_3_stub_signal);
	MC0_ddrc->sys_clk_n(MC0_ddrc_sys_clk_n_connect_signal);
	MC0_ddrc->sys_clk_p(MC0_ddrc_sys_clk_p_connect_signal);
	MC1_ddrc->ch0_lpddr4_dmi_a(CH0_LPDDR4_1_dmi_a);
	MC1_ddrc->ch0_lpddr4_dmi_b(CH0_LPDDR4_1_dmi_b);
	MC1_ddrc->ch0_lpddr4_dq_a(CH0_LPDDR4_1_dq_a);
	MC1_ddrc->ch0_lpddr4_dq_b(CH0_LPDDR4_1_dq_b);
	MC1_ddrc->ch0_lpddr4_dqs_c_a(CH0_LPDDR4_1_dqs_c_a);
	MC1_ddrc->ch0_lpddr4_dqs_c_b(CH0_LPDDR4_1_dqs_c_b);
	MC1_ddrc->ch0_lpddr4_dqs_t_a(CH0_LPDDR4_1_dqs_t_a);
	MC1_ddrc->ch0_lpddr4_dqs_t_b(CH0_LPDDR4_1_dqs_t_b);
	MC1_ddrc->ch1_lpddr4_dmi_a(CH1_LPDDR4_1_dmi_a);
	MC1_ddrc->ch1_lpddr4_dmi_b(CH1_LPDDR4_1_dmi_b);
	MC1_ddrc->ch1_lpddr4_dq_a(CH1_LPDDR4_1_dq_a);
	MC1_ddrc->ch1_lpddr4_dq_b(CH1_LPDDR4_1_dq_b);
	MC1_ddrc->ch1_lpddr4_dqs_c_a(CH1_LPDDR4_1_dqs_c_a);
	MC1_ddrc->ch1_lpddr4_dqs_c_b(CH1_LPDDR4_1_dqs_c_b);
	MC1_ddrc->ch1_lpddr4_dqs_t_a(CH1_LPDDR4_1_dqs_t_a);
	MC1_ddrc->ch1_lpddr4_dqs_t_b(CH1_LPDDR4_1_dqs_t_b);
	MC1_ddrc->dmc2noc_credit_rdy_0(MC1_ddrc_dmc2noc_credit_rdy_0_driver_signal);
	MC1_ddrc->dmc2noc_credit_rdy_1(MC1_ddrc_dmc2noc_credit_rdy_1_driver_signal);
	MC1_ddrc->dmc2noc_credit_rdy_2(MC1_ddrc_dmc2noc_credit_rdy_2_driver_signal);
	MC1_ddrc->dmc2noc_credit_rdy_3(MC1_ddrc_dmc2noc_credit_rdy_3_driver_signal);
	MC1_ddrc->dmc2noc_credit_rtn_0(MC1_ddrc_dmc2noc_credit_rtn_0_driver_signal);
	MC1_ddrc->dmc2noc_credit_rtn_1(MC1_ddrc_dmc2noc_credit_rtn_1_driver_signal);
	MC1_ddrc->dmc2noc_credit_rtn_2(MC1_ddrc_dmc2noc_credit_rtn_2_driver_signal);
	MC1_ddrc->dmc2noc_credit_rtn_3(MC1_ddrc_dmc2noc_credit_rtn_3_driver_signal);
	MC1_ddrc->dmc2noc_data_out_0(MC1_ddrc_dmc2noc_data_out_0_driver_signal);
	MC1_ddrc->dmc2noc_data_out_1(MC1_ddrc_dmc2noc_data_out_1_driver_signal);
	MC1_ddrc->dmc2noc_data_out_2(MC1_ddrc_dmc2noc_data_out_2_driver_signal);
	MC1_ddrc->dmc2noc_data_out_3(MC1_ddrc_dmc2noc_data_out_3_driver_signal);
	MC1_ddrc->dmc2noc_valid_out_0(MC1_ddrc_dmc2noc_valid_out_0_driver_signal);
	MC1_ddrc->dmc2noc_valid_out_1(MC1_ddrc_dmc2noc_valid_out_1_driver_signal);
	MC1_ddrc->dmc2noc_valid_out_2(MC1_ddrc_dmc2noc_valid_out_2_driver_signal);
	MC1_ddrc->dmc2noc_valid_out_3(MC1_ddrc_dmc2noc_valid_out_3_driver_signal);
	MC1_ddrc->from_noc_0(MC1_ddrc_from_noc_0_stub_signal);
	MC1_ddrc->from_noc_1(MC1_ddrc_from_noc_1_stub_signal);
	MC1_ddrc->from_noc_2(MC1_ddrc_from_noc_2_stub_signal);
	MC1_ddrc->from_noc_3(MC1_ddrc_from_noc_3_stub_signal);
	MC1_ddrc->noc2dmc_credit_rdy_0(MC1_ddrc_noc2dmc_credit_rdy_0_stub_signal);
	MC1_ddrc->noc2dmc_credit_rdy_1(MC1_ddrc_noc2dmc_credit_rdy_1_stub_signal);
	MC1_ddrc->noc2dmc_credit_rdy_2(MC1_ddrc_noc2dmc_credit_rdy_2_stub_signal);
	MC1_ddrc->noc2dmc_credit_rdy_3(MC1_ddrc_noc2dmc_credit_rdy_3_stub_signal);
	MC1_ddrc->noc2dmc_credit_rtn_0(MC1_ddrc_noc2dmc_credit_rtn_0_stub_signal);
	MC1_ddrc->noc2dmc_credit_rtn_1(MC1_ddrc_noc2dmc_credit_rtn_1_stub_signal);
	MC1_ddrc->noc2dmc_credit_rtn_2(MC1_ddrc_noc2dmc_credit_rtn_2_stub_signal);
	MC1_ddrc->noc2dmc_credit_rtn_3(MC1_ddrc_noc2dmc_credit_rtn_3_stub_signal);
	MC1_ddrc->noc2dmc_data_in_0(MC1_ddrc_noc2dmc_data_in_0_stub_signal);
	MC1_ddrc->noc2dmc_data_in_1(MC1_ddrc_noc2dmc_data_in_1_stub_signal);
	MC1_ddrc->noc2dmc_data_in_2(MC1_ddrc_noc2dmc_data_in_2_stub_signal);
	MC1_ddrc->noc2dmc_data_in_3(MC1_ddrc_noc2dmc_data_in_3_stub_signal);
	MC1_ddrc->noc2dmc_valid_in_0(MC1_ddrc_noc2dmc_valid_in_0_stub_signal);
	MC1_ddrc->noc2dmc_valid_in_1(MC1_ddrc_noc2dmc_valid_in_1_stub_signal);
	MC1_ddrc->noc2dmc_valid_in_2(MC1_ddrc_noc2dmc_valid_in_2_stub_signal);
	MC1_ddrc->noc2dmc_valid_in_3(MC1_ddrc_noc2dmc_valid_in_3_stub_signal);
	MC1_ddrc->sys_clk_n(MC1_ddrc_sys_clk_n_connect_signal);
	MC1_ddrc->sys_clk_p(MC1_ddrc_sys_clk_p_connect_signal);
	MC0_ddrc->ch0_lpddr4_ca_a(CH0_LPDDR4_0_ca_a);
	MC0_ddrc->ch0_lpddr4_ca_b(CH0_LPDDR4_0_ca_b);
	MC0_ddrc->ch0_lpddr4_ck_c_a(CH0_LPDDR4_0_ck_c_a);
	MC0_ddrc->ch0_lpddr4_ck_c_b(CH0_LPDDR4_0_ck_c_b);
	MC0_ddrc->ch0_lpddr4_ck_t_a(CH0_LPDDR4_0_ck_t_a);
	MC0_ddrc->ch0_lpddr4_ck_t_b(CH0_LPDDR4_0_ck_t_b);
	MC0_ddrc->ch0_lpddr4_cke_a(CH0_LPDDR4_0_cke_a);
	MC0_ddrc->ch0_lpddr4_cke_b(CH0_LPDDR4_0_cke_b);
	MC0_ddrc->ch0_lpddr4_cs_a(CH0_LPDDR4_0_cs_a);
	MC0_ddrc->ch0_lpddr4_cs_b(CH0_LPDDR4_0_cs_b);
	MC0_ddrc->ch0_lpddr4_reset_n(CH0_LPDDR4_0_reset_n);
	MC1_ddrc->ch0_lpddr4_ca_a(CH0_LPDDR4_1_ca_a);
	MC1_ddrc->ch0_lpddr4_ca_b(CH0_LPDDR4_1_ca_b);
	MC1_ddrc->ch0_lpddr4_ck_c_a(CH0_LPDDR4_1_ck_c_a);
	MC1_ddrc->ch0_lpddr4_ck_c_b(CH0_LPDDR4_1_ck_c_b);
	MC1_ddrc->ch0_lpddr4_ck_t_a(CH0_LPDDR4_1_ck_t_a);
	MC1_ddrc->ch0_lpddr4_ck_t_b(CH0_LPDDR4_1_ck_t_b);
	MC1_ddrc->ch0_lpddr4_cke_a(CH0_LPDDR4_1_cke_a);
	MC1_ddrc->ch0_lpddr4_cke_b(CH0_LPDDR4_1_cke_b);
	MC1_ddrc->ch0_lpddr4_cs_a(CH0_LPDDR4_1_cs_a);
	MC1_ddrc->ch0_lpddr4_cs_b(CH0_LPDDR4_1_cs_b);
	MC1_ddrc->ch0_lpddr4_reset_n(CH0_LPDDR4_1_reset_n);
	MC0_ddrc->ch1_lpddr4_ca_a(CH1_LPDDR4_0_ca_a);
	MC0_ddrc->ch1_lpddr4_ca_b(CH1_LPDDR4_0_ca_b);
	MC0_ddrc->ch1_lpddr4_ck_c_a(CH1_LPDDR4_0_ck_c_a);
	MC0_ddrc->ch1_lpddr4_ck_c_b(CH1_LPDDR4_0_ck_c_b);
	MC0_ddrc->ch1_lpddr4_ck_t_a(CH1_LPDDR4_0_ck_t_a);
	MC0_ddrc->ch1_lpddr4_ck_t_b(CH1_LPDDR4_0_ck_t_b);
	MC0_ddrc->ch1_lpddr4_cke_a(CH1_LPDDR4_0_cke_a);
	MC0_ddrc->ch1_lpddr4_cke_b(CH1_LPDDR4_0_cke_b);
	MC0_ddrc->ch1_lpddr4_cs_a(CH1_LPDDR4_0_cs_a);
	MC0_ddrc->ch1_lpddr4_cs_b(CH1_LPDDR4_0_cs_b);
	MC0_ddrc->ch1_lpddr4_reset_n(CH1_LPDDR4_0_reset_n);
	MC1_ddrc->ch1_lpddr4_ca_a(CH1_LPDDR4_1_ca_a);
	MC1_ddrc->ch1_lpddr4_ca_b(CH1_LPDDR4_1_ca_b);
	MC1_ddrc->ch1_lpddr4_ck_c_a(CH1_LPDDR4_1_ck_c_a);
	MC1_ddrc->ch1_lpddr4_ck_c_b(CH1_LPDDR4_1_ck_c_b);
	MC1_ddrc->ch1_lpddr4_ck_t_a(CH1_LPDDR4_1_ck_t_a);
	MC1_ddrc->ch1_lpddr4_ck_t_b(CH1_LPDDR4_1_ck_t_b);
	MC1_ddrc->ch1_lpddr4_cke_a(CH1_LPDDR4_1_cke_a);
	MC1_ddrc->ch1_lpddr4_cke_b(CH1_LPDDR4_1_cke_b);
	MC1_ddrc->ch1_lpddr4_cs_a(CH1_LPDDR4_1_cs_a);
	MC1_ddrc->ch1_lpddr4_cs_b(CH1_LPDDR4_1_cs_b);
	MC1_ddrc->ch1_lpddr4_reset_n(CH1_LPDDR4_1_reset_n);
	
	
	
	//Exported socket connection
	//Add TLM Parameters
	
	//Thread Initialization
	//Add TLM Parameters
	SC_METHOD(MC0_ddrc_sys_clk_n_DRIVER_METHOD);
	sensitive<<sys_clk0_clk_n.value_changed();
	
	SC_METHOD(MC0_ddrc_sys_clk_p_DRIVER_METHOD);
	sensitive<<sys_clk0_clk_p.value_changed();
	
	SC_METHOD(MC1_ddrc_sys_clk_n_DRIVER_METHOD);
	sensitive<<sys_clk1_clk_n.value_changed();
	
	SC_METHOD(MC1_ddrc_sys_clk_p_DRIVER_METHOD);
	sensitive<<sys_clk1_clk_p.value_changed();
	
	
	//Socket Connection
	xsc::utils::xsc_sim_manager::addInstance("bd_28ba", this);
}
void bd_28ba::MC0_ddrc_sys_clk_n_DRIVER_METHOD() {
  bool value;
  value=((sys_clk0_clk_n.read().get_bit(0)==sc_dt::sc_logic_value_t::Log_1)?true:false);
  MC0_ddrc_sys_clk_n_connect_signal.write(value);
}
void bd_28ba::MC0_ddrc_sys_clk_p_DRIVER_METHOD() {
  bool value;
  value=((sys_clk0_clk_p.read().get_bit(0)==sc_dt::sc_logic_value_t::Log_1)?true:false);
  MC0_ddrc_sys_clk_p_connect_signal.write(value);
}
void bd_28ba::MC1_ddrc_sys_clk_n_DRIVER_METHOD() {
  bool value;
  value=((sys_clk1_clk_n.read().get_bit(0)==sc_dt::sc_logic_value_t::Log_1)?true:false);
  MC1_ddrc_sys_clk_n_connect_signal.write(value);
}
void bd_28ba::MC1_ddrc_sys_clk_p_DRIVER_METHOD() {
  bool value;
  value=((sys_clk1_clk_p.read().get_bit(0)==sc_dt::sc_logic_value_t::Log_1)?true:false);
  MC1_ddrc_sys_clk_p_connect_signal.write(value);
}
bd_28ba::~bd_28ba()
{
	if(MC0_ddrc) delete MC0_ddrc;
	if(MC1_ddrc) delete MC1_ddrc;
}
