//File Automatically generated by SystemC Netlister Time
#ifndef BD_27EC_SCI_H
#define BD_27EC_SCI_H
#include "systemc.h"
#include "xtlm.h"

class bd_27ec_sci : public sc_module {

public:
bd_27ec_sci(sc_core::sc_module_name name);
~bd_27ec_sci();
//Exported sockets declaration
xtlm::xtlm_aximm_initiator_socket* M00_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_initiator_socket* M00_AXI_tlm_aximm_write_socket;
xtlm::xtlm_aximm_target_socket* S00_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S00_AXI_tlm_aximm_write_socket;
xtlm::xtlm_aximm_target_socket* S01_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S01_AXI_tlm_aximm_write_socket;
xtlm::xtlm_aximm_target_socket* S02_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S02_AXI_tlm_aximm_write_socket;
xtlm::xtlm_aximm_target_socket* S03_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S03_AXI_tlm_aximm_write_socket;
xtlm::xtlm_aximm_target_socket* S04_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S04_AXI_tlm_aximm_write_socket;
xtlm::xtlm_aximm_target_socket* S05_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S05_AXI_tlm_aximm_write_socket;
xtlm::xtlm_aximm_target_socket* S06_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S06_AXI_tlm_aximm_write_socket;
xtlm::xtlm_aximm_target_socket* S07_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S07_AXI_tlm_aximm_write_socket;

protected:

private:
	bd_27ec_sci(const bd_27ec_sci&);
	const bd_27ec_sci& operator=(const bd_27ec_sci&);
};
#endif
