//File Automatically generated by SystemC Netlister Time
#ifndef BD_90D1_H
#define BD_90D1_H
#include "systemc.h"
#include "xtlm.h"
#include "bd_90d1_S02_AXI_nmu_0.h"
#include "bd_90d1_const_0_0.h"
#include "bd_90d1_S01_AXI_nmu_0.h"
#include "bd_90d1_S00_AXI_nmu_0.h"
#include "bd_90d1_MC0_ddrc_0.h"
#include "bd_90d1_sci.h"

class bd_90d1 : public bd_90d1_sci {

public:
	
	//Port declaration
	sc_out< sc_bv<1> > CH0_DDR4_0_act_n;
	sc_out< sc_bv<17> > CH0_DDR4_0_adr;
	sc_out< sc_bv<2> > CH0_DDR4_0_ba;
	sc_out< sc_bv<2> > CH0_DDR4_0_bg;
	sc_out< sc_bv<1> > CH0_DDR4_0_ck_c;
	sc_out< sc_bv<1> > CH0_DDR4_0_ck_t;
	sc_out< sc_bv<1> > CH0_DDR4_0_cke;
	sc_out< sc_bv<1> > CH0_DDR4_0_cs_n;
	sc_inout< sc_bv<8> > CH0_DDR4_0_dm_n;
	sc_inout< sc_bv<64> > CH0_DDR4_0_dq;
	sc_inout< sc_bv<8> > CH0_DDR4_0_dqs_c;
	sc_inout< sc_bv<8> > CH0_DDR4_0_dqs_t;
	sc_out< sc_bv<1> > CH0_DDR4_0_odt;
	sc_out< sc_bv<1> > CH0_DDR4_0_reset_n;
	sc_in< sc_bv<1> > S00_INI_internoc;
	sc_in< sc_bv<1> > S01_INI_internoc;
	sc_in< sc_bv<1> > S02_INI_internoc;
	sc_in< sc_bv<1> > S03_INI_internoc;
	sc_in<bool>     aclk0;
	sc_in< sc_bv<1> > sys_clk0_clk_n;
	sc_in< sc_bv<1> > sys_clk0_clk_p;
	
	//Instance declaration
	bd_90d1_MC0_ddrc_0* MC0_ddrc;
	bd_90d1_S00_AXI_nmu_0* S00_AXI_nmu;
	bd_90d1_S01_AXI_nmu_0* S01_AXI_nmu;
	bd_90d1_S02_AXI_nmu_0* S02_AXI_nmu;
	bd_90d1_const_0_0* const_0;
	
	//Signal Declaration
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_0_driver_signal;
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_1_driver_signal;
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_2_driver_signal;
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_3_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_0_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_1_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_2_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_3_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_0_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_1_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_2_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_3_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_0_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_1_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_2_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_3_driver_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_0_stub_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_1_stub_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_2_stub_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_3_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_0_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_1_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_2_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_3_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_0_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_1_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_2_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_3_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_0_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_1_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_2_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_3_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_0_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_1_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_2_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_3_stub_signal;
	sc_signal<bool>     MC0_ddrc_sys_clk_n_connect_signal;
	sc_signal<bool>     MC0_ddrc_sys_clk_p_connect_signal;
	sc_signal< sc_bv<64> > S00_AXI_nmu_IF_NOC_AXI_ARADDR_stub_signal;
	sc_signal< sc_bv<2> > S00_AXI_nmu_IF_NOC_AXI_ARBURST_stub_signal;
	sc_signal< sc_bv<4> > S00_AXI_nmu_IF_NOC_AXI_ARCACHE_stub_signal;
	sc_signal< sc_bv<1> > S00_AXI_nmu_IF_NOC_AXI_ARID_stub_signal;
	sc_signal< sc_bv<8> > S00_AXI_nmu_IF_NOC_AXI_ARLEN_stub_signal;
	sc_signal< sc_bv<1> > S00_AXI_nmu_IF_NOC_AXI_ARLOCK_stub_signal;
	sc_signal< sc_bv<3> > S00_AXI_nmu_IF_NOC_AXI_ARPROT_stub_signal;
	sc_signal< sc_bv<4> > S00_AXI_nmu_IF_NOC_AXI_ARQOS_stub_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_AXI_ARREADY_driver_signal;
	sc_signal< sc_bv<4> > S00_AXI_nmu_IF_NOC_AXI_ARREGION_stub_signal;
	sc_signal< sc_bv<3> > S00_AXI_nmu_IF_NOC_AXI_ARSIZE_stub_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_AXI_ARVALID_stub_signal;
	sc_signal< sc_bv<64> > S00_AXI_nmu_IF_NOC_AXI_AWADDR_stub_signal;
	sc_signal< sc_bv<2> > S00_AXI_nmu_IF_NOC_AXI_AWBURST_stub_signal;
	sc_signal< sc_bv<4> > S00_AXI_nmu_IF_NOC_AXI_AWCACHE_stub_signal;
	sc_signal< sc_bv<1> > S00_AXI_nmu_IF_NOC_AXI_AWID_stub_signal;
	sc_signal< sc_bv<8> > S00_AXI_nmu_IF_NOC_AXI_AWLEN_stub_signal;
	sc_signal< sc_bv<1> > S00_AXI_nmu_IF_NOC_AXI_AWLOCK_stub_signal;
	sc_signal< sc_bv<3> > S00_AXI_nmu_IF_NOC_AXI_AWPROT_stub_signal;
	sc_signal< sc_bv<4> > S00_AXI_nmu_IF_NOC_AXI_AWQOS_stub_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_AXI_AWREADY_driver_signal;
	sc_signal< sc_bv<4> > S00_AXI_nmu_IF_NOC_AXI_AWREGION_stub_signal;
	sc_signal< sc_bv<3> > S00_AXI_nmu_IF_NOC_AXI_AWSIZE_stub_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_AXI_AWVALID_stub_signal;
	sc_signal< sc_bv<1> > S00_AXI_nmu_IF_NOC_AXI_BID_driver_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_AXI_BREADY_stub_signal;
	sc_signal< sc_bv<2> > S00_AXI_nmu_IF_NOC_AXI_BRESP_driver_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_AXI_BVALID_driver_signal;
	sc_signal< sc_bv<32> > S00_AXI_nmu_IF_NOC_AXI_RDATA_driver_signal;
	sc_signal< sc_bv<1> > S00_AXI_nmu_IF_NOC_AXI_RID_driver_signal;
	sc_signal< sc_bv<1> > S00_AXI_nmu_IF_NOC_AXI_RLAST_driver_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_AXI_RREADY_stub_signal;
	sc_signal< sc_bv<2> > S00_AXI_nmu_IF_NOC_AXI_RRESP_driver_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_AXI_RVALID_driver_signal;
	sc_signal< sc_bv<32> > S00_AXI_nmu_IF_NOC_AXI_WDATA_stub_signal;
	sc_signal< sc_bv<1> > S00_AXI_nmu_IF_NOC_AXI_WLAST_stub_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_AXI_WREADY_driver_signal;
	sc_signal< sc_bv<4> > S00_AXI_nmu_IF_NOC_AXI_WSTRB_stub_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_AXI_WVALID_stub_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_NPP_IN_NOC_CREDIT_RDY_stub_signal;
	sc_signal< sc_bv<8> > S00_AXI_nmu_IF_NOC_NPP_IN_NOC_CREDIT_RETURN_driver_signal;
	sc_signal< sc_bv<182> > S00_AXI_nmu_IF_NOC_NPP_IN_NOC_FLIT_stub_signal;
	sc_signal< sc_bv<8> > S00_AXI_nmu_IF_NOC_NPP_IN_NOC_VALID_stub_signal;
	sc_signal<bool>     S00_AXI_nmu_IF_NOC_NPP_OUT_NOC_CREDIT_RDY_driver_signal;
	sc_signal< sc_bv<8> > S00_AXI_nmu_IF_NOC_NPP_OUT_NOC_CREDIT_RETURN_stub_signal;
	sc_signal< sc_bv<182> > S00_AXI_nmu_IF_NOC_NPP_OUT_NOC_FLIT_driver_signal;
	sc_signal< sc_bv<8> > S00_AXI_nmu_IF_NOC_NPP_OUT_NOC_VALID_driver_signal;
	sc_signal<bool>     S00_AXI_nmu_NMU_driver_signal;
	sc_signal<bool>     S00_AXI_nmu_NMU_RD_DEST_MODE_connect_signal;
	sc_signal< sc_bv<1> > S00_AXI_nmu_NMU_RD_DEST_MODE_driver_signal;
	sc_signal< sc_bv<12> > S00_AXI_nmu_NMU_RD_USR_DST_stub_signal;
	sc_signal<bool>     S00_AXI_nmu_NMU_WR_DEST_MODE_connect_signal;
	sc_signal< sc_bv<12> > S00_AXI_nmu_NMU_WR_USR_DST_stub_signal;
	sc_signal< sc_bv<64> > S01_AXI_nmu_IF_NOC_AXI_ARADDR_stub_signal;
	sc_signal< sc_bv<2> > S01_AXI_nmu_IF_NOC_AXI_ARBURST_stub_signal;
	sc_signal< sc_bv<4> > S01_AXI_nmu_IF_NOC_AXI_ARCACHE_stub_signal;
	sc_signal< sc_bv<1> > S01_AXI_nmu_IF_NOC_AXI_ARID_stub_signal;
	sc_signal< sc_bv<8> > S01_AXI_nmu_IF_NOC_AXI_ARLEN_stub_signal;
	sc_signal< sc_bv<1> > S01_AXI_nmu_IF_NOC_AXI_ARLOCK_stub_signal;
	sc_signal< sc_bv<3> > S01_AXI_nmu_IF_NOC_AXI_ARPROT_stub_signal;
	sc_signal< sc_bv<4> > S01_AXI_nmu_IF_NOC_AXI_ARQOS_stub_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_AXI_ARREADY_driver_signal;
	sc_signal< sc_bv<4> > S01_AXI_nmu_IF_NOC_AXI_ARREGION_stub_signal;
	sc_signal< sc_bv<3> > S01_AXI_nmu_IF_NOC_AXI_ARSIZE_stub_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_AXI_ARVALID_stub_signal;
	sc_signal< sc_bv<64> > S01_AXI_nmu_IF_NOC_AXI_AWADDR_stub_signal;
	sc_signal< sc_bv<2> > S01_AXI_nmu_IF_NOC_AXI_AWBURST_stub_signal;
	sc_signal< sc_bv<4> > S01_AXI_nmu_IF_NOC_AXI_AWCACHE_stub_signal;
	sc_signal< sc_bv<1> > S01_AXI_nmu_IF_NOC_AXI_AWID_stub_signal;
	sc_signal< sc_bv<8> > S01_AXI_nmu_IF_NOC_AXI_AWLEN_stub_signal;
	sc_signal< sc_bv<1> > S01_AXI_nmu_IF_NOC_AXI_AWLOCK_stub_signal;
	sc_signal< sc_bv<3> > S01_AXI_nmu_IF_NOC_AXI_AWPROT_stub_signal;
	sc_signal< sc_bv<4> > S01_AXI_nmu_IF_NOC_AXI_AWQOS_stub_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_AXI_AWREADY_driver_signal;
	sc_signal< sc_bv<4> > S01_AXI_nmu_IF_NOC_AXI_AWREGION_stub_signal;
	sc_signal< sc_bv<3> > S01_AXI_nmu_IF_NOC_AXI_AWSIZE_stub_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_AXI_AWVALID_stub_signal;
	sc_signal< sc_bv<1> > S01_AXI_nmu_IF_NOC_AXI_BID_driver_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_AXI_BREADY_stub_signal;
	sc_signal< sc_bv<2> > S01_AXI_nmu_IF_NOC_AXI_BRESP_driver_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_AXI_BVALID_driver_signal;
	sc_signal< sc_bv<32> > S01_AXI_nmu_IF_NOC_AXI_RDATA_driver_signal;
	sc_signal< sc_bv<1> > S01_AXI_nmu_IF_NOC_AXI_RID_driver_signal;
	sc_signal< sc_bv<1> > S01_AXI_nmu_IF_NOC_AXI_RLAST_driver_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_AXI_RREADY_stub_signal;
	sc_signal< sc_bv<2> > S01_AXI_nmu_IF_NOC_AXI_RRESP_driver_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_AXI_RVALID_driver_signal;
	sc_signal< sc_bv<32> > S01_AXI_nmu_IF_NOC_AXI_WDATA_stub_signal;
	sc_signal< sc_bv<1> > S01_AXI_nmu_IF_NOC_AXI_WLAST_stub_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_AXI_WREADY_driver_signal;
	sc_signal< sc_bv<4> > S01_AXI_nmu_IF_NOC_AXI_WSTRB_stub_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_AXI_WVALID_stub_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_NPP_IN_NOC_CREDIT_RDY_stub_signal;
	sc_signal< sc_bv<8> > S01_AXI_nmu_IF_NOC_NPP_IN_NOC_CREDIT_RETURN_driver_signal;
	sc_signal< sc_bv<182> > S01_AXI_nmu_IF_NOC_NPP_IN_NOC_FLIT_stub_signal;
	sc_signal< sc_bv<8> > S01_AXI_nmu_IF_NOC_NPP_IN_NOC_VALID_stub_signal;
	sc_signal<bool>     S01_AXI_nmu_IF_NOC_NPP_OUT_NOC_CREDIT_RDY_driver_signal;
	sc_signal< sc_bv<8> > S01_AXI_nmu_IF_NOC_NPP_OUT_NOC_CREDIT_RETURN_stub_signal;
	sc_signal< sc_bv<182> > S01_AXI_nmu_IF_NOC_NPP_OUT_NOC_FLIT_driver_signal;
	sc_signal< sc_bv<8> > S01_AXI_nmu_IF_NOC_NPP_OUT_NOC_VALID_driver_signal;
	sc_signal<bool>     S01_AXI_nmu_NMU_driver_signal;
	sc_signal<bool>     S01_AXI_nmu_NMU_RD_DEST_MODE_connect_signal;
	sc_signal< sc_bv<12> > S01_AXI_nmu_NMU_RD_USR_DST_stub_signal;
	sc_signal<bool>     S01_AXI_nmu_NMU_WR_DEST_MODE_connect_signal;
	sc_signal< sc_bv<12> > S01_AXI_nmu_NMU_WR_USR_DST_stub_signal;
	sc_signal< sc_bv<64> > S02_AXI_nmu_IF_NOC_AXI_ARADDR_stub_signal;
	sc_signal< sc_bv<2> > S02_AXI_nmu_IF_NOC_AXI_ARBURST_stub_signal;
	sc_signal< sc_bv<4> > S02_AXI_nmu_IF_NOC_AXI_ARCACHE_stub_signal;
	sc_signal< sc_bv<1> > S02_AXI_nmu_IF_NOC_AXI_ARID_stub_signal;
	sc_signal< sc_bv<8> > S02_AXI_nmu_IF_NOC_AXI_ARLEN_stub_signal;
	sc_signal< sc_bv<1> > S02_AXI_nmu_IF_NOC_AXI_ARLOCK_stub_signal;
	sc_signal< sc_bv<3> > S02_AXI_nmu_IF_NOC_AXI_ARPROT_stub_signal;
	sc_signal< sc_bv<4> > S02_AXI_nmu_IF_NOC_AXI_ARQOS_stub_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_AXI_ARREADY_driver_signal;
	sc_signal< sc_bv<4> > S02_AXI_nmu_IF_NOC_AXI_ARREGION_stub_signal;
	sc_signal< sc_bv<3> > S02_AXI_nmu_IF_NOC_AXI_ARSIZE_stub_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_AXI_ARVALID_stub_signal;
	sc_signal< sc_bv<64> > S02_AXI_nmu_IF_NOC_AXI_AWADDR_stub_signal;
	sc_signal< sc_bv<2> > S02_AXI_nmu_IF_NOC_AXI_AWBURST_stub_signal;
	sc_signal< sc_bv<4> > S02_AXI_nmu_IF_NOC_AXI_AWCACHE_stub_signal;
	sc_signal< sc_bv<1> > S02_AXI_nmu_IF_NOC_AXI_AWID_stub_signal;
	sc_signal< sc_bv<8> > S02_AXI_nmu_IF_NOC_AXI_AWLEN_stub_signal;
	sc_signal< sc_bv<1> > S02_AXI_nmu_IF_NOC_AXI_AWLOCK_stub_signal;
	sc_signal< sc_bv<3> > S02_AXI_nmu_IF_NOC_AXI_AWPROT_stub_signal;
	sc_signal< sc_bv<4> > S02_AXI_nmu_IF_NOC_AXI_AWQOS_stub_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_AXI_AWREADY_driver_signal;
	sc_signal< sc_bv<4> > S02_AXI_nmu_IF_NOC_AXI_AWREGION_stub_signal;
	sc_signal< sc_bv<3> > S02_AXI_nmu_IF_NOC_AXI_AWSIZE_stub_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_AXI_AWVALID_stub_signal;
	sc_signal< sc_bv<1> > S02_AXI_nmu_IF_NOC_AXI_BID_driver_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_AXI_BREADY_stub_signal;
	sc_signal< sc_bv<2> > S02_AXI_nmu_IF_NOC_AXI_BRESP_driver_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_AXI_BVALID_driver_signal;
	sc_signal< sc_bv<32> > S02_AXI_nmu_IF_NOC_AXI_RDATA_driver_signal;
	sc_signal< sc_bv<1> > S02_AXI_nmu_IF_NOC_AXI_RID_driver_signal;
	sc_signal< sc_bv<1> > S02_AXI_nmu_IF_NOC_AXI_RLAST_driver_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_AXI_RREADY_stub_signal;
	sc_signal< sc_bv<2> > S02_AXI_nmu_IF_NOC_AXI_RRESP_driver_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_AXI_RVALID_driver_signal;
	sc_signal< sc_bv<32> > S02_AXI_nmu_IF_NOC_AXI_WDATA_stub_signal;
	sc_signal< sc_bv<1> > S02_AXI_nmu_IF_NOC_AXI_WLAST_stub_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_AXI_WREADY_driver_signal;
	sc_signal< sc_bv<4> > S02_AXI_nmu_IF_NOC_AXI_WSTRB_stub_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_AXI_WVALID_stub_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_NPP_IN_NOC_CREDIT_RDY_stub_signal;
	sc_signal< sc_bv<8> > S02_AXI_nmu_IF_NOC_NPP_IN_NOC_CREDIT_RETURN_driver_signal;
	sc_signal< sc_bv<182> > S02_AXI_nmu_IF_NOC_NPP_IN_NOC_FLIT_stub_signal;
	sc_signal< sc_bv<8> > S02_AXI_nmu_IF_NOC_NPP_IN_NOC_VALID_stub_signal;
	sc_signal<bool>     S02_AXI_nmu_IF_NOC_NPP_OUT_NOC_CREDIT_RDY_driver_signal;
	sc_signal< sc_bv<8> > S02_AXI_nmu_IF_NOC_NPP_OUT_NOC_CREDIT_RETURN_stub_signal;
	sc_signal< sc_bv<182> > S02_AXI_nmu_IF_NOC_NPP_OUT_NOC_FLIT_driver_signal;
	sc_signal< sc_bv<8> > S02_AXI_nmu_IF_NOC_NPP_OUT_NOC_VALID_driver_signal;
	sc_signal<bool>     S02_AXI_nmu_NMU_driver_signal;
	sc_signal<bool>     S02_AXI_nmu_NMU_RD_DEST_MODE_connect_signal;
	sc_signal< sc_bv<12> > S02_AXI_nmu_NMU_RD_USR_DST_stub_signal;
	sc_signal<bool>     S02_AXI_nmu_NMU_WR_DEST_MODE_connect_signal;
	sc_signal< sc_bv<12> > S02_AXI_nmu_NMU_WR_USR_DST_stub_signal;
	sc_signal<bool>     MC0_ddrc_ch0_ddr4_act_n_driver_signal;
	sc_signal<bool>     MC0_ddrc_ch0_ddr4_reset_n_driver_signal;
	
	
	//Thread Methods
	void MC0_ddrc_sys_clk_n_DRIVER_METHOD();
	void MC0_ddrc_sys_clk_p_DRIVER_METHOD();
	void S00_AXI_nmu_NMU_RD_DEST_MODE_DRIVER_METHOD();
	void S00_AXI_nmu_NMU_WR_DEST_MODE_DRIVER_METHOD();
	void S01_AXI_nmu_NMU_RD_DEST_MODE_DRIVER_METHOD();
	void S01_AXI_nmu_NMU_WR_DEST_MODE_DRIVER_METHOD();
	void S02_AXI_nmu_NMU_RD_DEST_MODE_DRIVER_METHOD();
	void S02_AXI_nmu_NMU_WR_DEST_MODE_DRIVER_METHOD();
	void bd_90d1_CH0_DDR4_0_act_n_EXT_METHOD();
	void bd_90d1_CH0_DDR4_0_reset_n_EXT_METHOD();
	
	//Constructor for the module
	bd_90d1(const sc_module_name& module_name,xsc::common_cpp::properties& properties);
	SC_HAS_PROCESS(bd_90d1);
	//Destructor for the module
	~bd_90d1();
	

protected:

private:
	bd_90d1(const bd_90d1&);
	const bd_90d1& operator=(const bd_90d1&);
};
#endif
