//File Automatically generated by SystemC Netlister Time
#include "bd_90d1_sci.h"
#include "bd_90d1_sci.h"
bd_90d1_sci::bd_90d1_sci(sc_core::sc_module_name name):sc_module(name) {
//Exported sockets Instantiation
S00_AXI_tlm_aximm_read_socket= new xtlm::xtlm_aximm_target_socket("rd_socket",32);
S00_AXI_tlm_aximm_write_socket= new xtlm::xtlm_aximm_target_socket("wr_socket",32);
S01_AXI_tlm_aximm_read_socket= new xtlm::xtlm_aximm_target_socket("rd_socket",32);
S01_AXI_tlm_aximm_write_socket= new xtlm::xtlm_aximm_target_socket("wr_socket",32);
S02_AXI_tlm_aximm_read_socket= new xtlm::xtlm_aximm_target_socket("rd_socket",32);
S02_AXI_tlm_aximm_write_socket= new xtlm::xtlm_aximm_target_socket("wr_socket",32);
xsc::utils::xsc_sim_manager::addInstance("bd_90d1_sci", this);
}
bd_90d1_sci::~bd_90d1_sci() {
}
