//File Automatically generated by SystemC Netlister Time
#ifndef BD_90D1_SCI_H
#define BD_90D1_SCI_H
#include "systemc.h"
#include "xtlm.h"

class bd_90d1_sci : public sc_module {

public:
bd_90d1_sci(sc_core::sc_module_name name);
~bd_90d1_sci();
//Exported sockets declaration
xtlm::xtlm_aximm_target_socket* S00_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S00_AXI_tlm_aximm_write_socket;
xtlm::xtlm_aximm_target_socket* S01_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S01_AXI_tlm_aximm_write_socket;
xtlm::xtlm_aximm_target_socket* S02_AXI_tlm_aximm_read_socket;
xtlm::xtlm_aximm_target_socket* S02_AXI_tlm_aximm_write_socket;

protected:

private:
	bd_90d1_sci(const bd_90d1_sci&);
	const bd_90d1_sci& operator=(const bd_90d1_sci&);
};
#endif
