//File Automatically generated by SystemC Netlister Time
#ifndef BD_28BA_SCI_H
#define BD_28BA_SCI_H
#include "systemc.h"
#include "xtlm.h"

class bd_28ba_sci : public sc_module {

public:
bd_28ba_sci(sc_core::sc_module_name name);
~bd_28ba_sci();
//Exported sockets declaration

protected:

private:
	bd_28ba_sci(const bd_28ba_sci&);
	const bd_28ba_sci& operator=(const bd_28ba_sci&);
};
#endif
