//File Automatically generated by SystemC Netlister Time
#ifndef BD_90D1_H
#define BD_90D1_H
#include "systemc.h"
#include "xtlm.h"
#include "bd_90d1_MC0_ddrc_0.h"
#include "bd_90d1_sci.h"

class bd_90d1 : public bd_90d1_sci {

public:
	
	//Port declaration
	sc_out< sc_bv<1> > CH0_DDR4_0_act_n;
	sc_out< sc_bv<17> > CH0_DDR4_0_adr;
	sc_out< sc_bv<2> > CH0_DDR4_0_ba;
	sc_out< sc_bv<2> > CH0_DDR4_0_bg;
	sc_out< sc_bv<1> > CH0_DDR4_0_ck_c;
	sc_out< sc_bv<1> > CH0_DDR4_0_ck_t;
	sc_out< sc_bv<1> > CH0_DDR4_0_cke;
	sc_out< sc_bv<1> > CH0_DDR4_0_cs_n;
	sc_inout< sc_bv<8> > CH0_DDR4_0_dm_n;
	sc_inout< sc_bv<64> > CH0_DDR4_0_dq;
	sc_inout< sc_bv<8> > CH0_DDR4_0_dqs_c;
	sc_inout< sc_bv<8> > CH0_DDR4_0_dqs_t;
	sc_out< sc_bv<1> > CH0_DDR4_0_odt;
	sc_out< sc_bv<1> > CH0_DDR4_0_reset_n;
	sc_in< sc_bv<1> > S00_INI_internoc;
	sc_in< sc_bv<1> > S01_INI_internoc;
	sc_in< sc_bv<1> > S02_INI_internoc;
	sc_in< sc_bv<1> > S03_INI_internoc;
	sc_in< sc_bv<1> > sys_clk0_clk_n;
	sc_in< sc_bv<1> > sys_clk0_clk_p;
	
	//Instance declaration
	bd_90d1_MC0_ddrc_0* MC0_ddrc;
	
	//Signal Declaration
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_0_driver_signal;
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_1_driver_signal;
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_2_driver_signal;
	sc_signal<bool>     MC0_ddrc_dmc2noc_credit_rdy_3_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_0_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_1_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_2_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_credit_rtn_3_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_0_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_1_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_2_driver_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_dmc2noc_data_out_3_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_0_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_1_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_2_driver_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_dmc2noc_valid_out_3_driver_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_0_stub_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_1_stub_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_2_stub_signal;
	sc_signal<bool>     MC0_ddrc_from_noc_3_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_0_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_1_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_2_stub_signal;
	sc_signal<bool>     MC0_ddrc_noc2dmc_credit_rdy_3_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_0_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_1_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_2_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_credit_rtn_3_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_0_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_1_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_2_stub_signal;
	sc_signal< sc_bv<182> > MC0_ddrc_noc2dmc_data_in_3_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_0_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_1_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_2_stub_signal;
	sc_signal< sc_bv<8> > MC0_ddrc_noc2dmc_valid_in_3_stub_signal;
	sc_signal<bool>     MC0_ddrc_sys_clk_n_connect_signal;
	sc_signal<bool>     MC0_ddrc_sys_clk_p_connect_signal;
	sc_signal<bool>     MC0_ddrc_ch0_ddr4_act_n_driver_signal;
	sc_signal<bool>     MC0_ddrc_ch0_ddr4_reset_n_driver_signal;
	
	
	//Thread Methods
	void MC0_ddrc_sys_clk_n_DRIVER_METHOD();
	void MC0_ddrc_sys_clk_p_DRIVER_METHOD();
	void bd_90d1_CH0_DDR4_0_act_n_EXT_METHOD();
	void bd_90d1_CH0_DDR4_0_reset_n_EXT_METHOD();
	
	//Constructor for the module
	bd_90d1(const sc_module_name& module_name,xsc::common_cpp::properties& properties);
	SC_HAS_PROCESS(bd_90d1);
	//Destructor for the module
	~bd_90d1();
	

protected:

private:
	bd_90d1(const bd_90d1&);
	const bd_90d1& operator=(const bd_90d1&);
};
#endif
