//File Automatically generated by SystemC Netlister Time
#ifndef BD_90D1_SCI_H
#define BD_90D1_SCI_H
#include "systemc.h"
#include "xtlm.h"

class bd_90d1_sci : public sc_module {

public:
bd_90d1_sci(sc_core::sc_module_name name);
~bd_90d1_sci();
//Exported sockets declaration

protected:

private:
	bd_90d1_sci(const bd_90d1_sci&);
	const bd_90d1_sci& operator=(const bd_90d1_sci&);
};
#endif
