//File Automatically generated by SystemC Netlister Time
#include "bd_90d1_sci.h"
#include "bd_90d1_sci.h"
bd_90d1_sci::bd_90d1_sci(sc_core::sc_module_name name):sc_module(name) {
//Exported sockets Instantiation
xsc::utils::xsc_sim_manager::addInstance("bd_90d1_sci", this);
}
bd_90d1_sci::~bd_90d1_sci() {
}
