//File Automatically generated by SystemC Netlister Time
#ifndef VITIS_DESIGN_SCI_H
#define VITIS_DESIGN_SCI_H
#include "systemc.h"
#include "xtlm.h"
#include "utils/xtlm_aximm_transview.h"
#include "utils/xtlm_aximm_transaction_logger.h"
#include "utils/xtlm_axis_transaction_logger.h"
#include "vitis_design_dpa_ctrl_interconnect_0_sc.h"
#include "vitis_design_dpa_hub_0_sc.h"
#include "vitis_design_dpa_mon0_0_sc.h"
#include "vitis_design_dpa_mon1_0_sc.h"
#include "vitis_design_dpa_mon2_0_sc.h"
#include "vitis_design_dpa_mon3_0_sc.h"
#include "vitis_design_dpa_mon4_0_sc.h"
#include "vitis_design_dpa_mon5_0_sc.h"
#include "vitis_design_CIPS_0_0_sc.h"
#include "vitis_design_cips_noc_0_sc.h"
#include "vitis_design_icn_ctrl_1_0_sc.h"
#include "vitis_design_ai_engine_0_0_sc.h"
#include "vitis_design_icn_ctrl_2_0_sc.h"
#include "vitis_design_icn_ctrl_3_0_sc.h"
#include "vitis_design_icn_ctrl_4_0_sc.h"
#include "vitis_design_icn_ctrl_5_0_sc.h"
#include "vitis_design_dummy_slave_0_0_sc.h"
#include "vitis_design_dummy_slave_1_0_sc.h"
#include "vitis_design_dummy_slave_2_0_sc.h"
#include "vitis_design_dummy_slave_3_0_sc.h"
#if (defined MTI_SYSTEMC || defined XM_SYSTEMC) && defined XSC_ENABLE_TLM_WAVEFORM 
#include "scv.h"
#endif
#if defined XM_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM 
#include "cve.h"
#endif


class vitis_design_sci : public xsc::utils::xsc_sim_conn_base {

public:
	//Exported sockets declaration
	
	//Constructor for the module
	vitis_design_sci(const sc_module_name& module_name);
	SC_HAS_PROCESS(vitis_design_sci);
	//Destructor for the module
	~vitis_design_sci();
	
	void initConnModule();

protected:
void before_end_of_elaboration();

private:
	vitis_design_sci(const vitis_design_sci&);
	const vitis_design_sci& operator=(const vitis_design_sci&);
};
#endif
