//File Automatically generated by SystemC Netlister Time
#include "vitis_design_sci.h"
vitis_design_sci::vitis_design_sci(const sc_module_name& module_name) : xsc::utils::xsc_sim_conn_base(module_name) 
{
	//Exported sockets Instantiation
	//Add TLM Parameters
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M00_AXI_tlm_MODE","vitis_design_dpa_hub_0","S_AXIFIFO_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M00_AXI_tlm_MODE","vitis_design_dpa_hub_0","S_AXIFIFO_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M01_AXI_tlm_MODE","vitis_design_dpa_hub_0","S_AXIHUB_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M01_AXI_tlm_MODE","vitis_design_dpa_hub_0","S_AXIHUB_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M02_AXI_tlm_MODE","vitis_design_dpa_mon0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M02_AXI_tlm_MODE","vitis_design_dpa_mon0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M03_AXI_tlm_MODE","vitis_design_dpa_mon1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M03_AXI_tlm_MODE","vitis_design_dpa_mon1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M04_AXI_tlm_MODE","vitis_design_dpa_mon2_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M04_AXI_tlm_MODE","vitis_design_dpa_mon2_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M05_AXI_tlm_MODE","vitis_design_dpa_mon3_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M05_AXI_tlm_MODE","vitis_design_dpa_mon3_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M06_AXI_tlm_MODE","vitis_design_dpa_mon4_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M06_AXI_tlm_MODE","vitis_design_dpa_mon4_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M07_AXI_tlm_MODE","vitis_design_dpa_mon5_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_ctrl_interconnect_0","M07_AXI_tlm_MODE","vitis_design_dpa_mon5_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon0_0","TRACE_OUT_0_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_0_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon0_0","TRACE_OUT_1_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_1_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon1_0","TRACE_OUT_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_2_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon2_0","TRACE_OUT_0_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_3_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon2_0","TRACE_OUT_1_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_4_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon3_0","TRACE_OUT_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_5_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon4_0","TRACE_OUT_0_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_6_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon4_0","TRACE_OUT_1_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_7_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_dpa_mon5_0","TRACE_OUT_TLM_MODE","vitis_design_dpa_hub_0","TRACE_IN_8_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","PMC_NOC_AXI_0_tlm_MODE","vitis_design_cips_noc_0","S07_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","PMC_NOC_AXI_0_tlm_MODE","vitis_design_cips_noc_0","S07_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_CCI_NOC_0_tlm_MODE","vitis_design_cips_noc_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_CCI_NOC_0_tlm_MODE","vitis_design_cips_noc_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_CCI_NOC_1_tlm_MODE","vitis_design_cips_noc_0","S01_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_CCI_NOC_1_tlm_MODE","vitis_design_cips_noc_0","S01_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_CCI_NOC_2_tlm_MODE","vitis_design_cips_noc_0","S02_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_CCI_NOC_2_tlm_MODE","vitis_design_cips_noc_0","S02_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_CCI_NOC_3_tlm_MODE","vitis_design_cips_noc_0","S03_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_CCI_NOC_3_tlm_MODE","vitis_design_cips_noc_0","S03_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_AXI_NOC_0_tlm_MODE","vitis_design_cips_noc_0","S04_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_AXI_NOC_0_tlm_MODE","vitis_design_cips_noc_0","S04_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_AXI_NOC_1_tlm_MODE","vitis_design_cips_noc_0","S05_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","FPD_AXI_NOC_1_tlm_MODE","vitis_design_cips_noc_0","S05_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","LPD_AXI_NOC_0_tlm_MODE","vitis_design_cips_noc_0","S06_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","LPD_AXI_NOC_0_tlm_MODE","vitis_design_cips_noc_0","S06_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","M_AXI_FPD_tlm_MODE","vitis_design_icn_ctrl_1_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_CIPS_0_0","M_AXI_FPD_tlm_MODE","vitis_design_icn_ctrl_1_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_cips_noc_0","M00_AXI_tlm_MODE","vitis_design_ai_engine_0_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_cips_noc_0","M00_AXI_tlm_MODE","vitis_design_ai_engine_0_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M02_AXI_tlm_MODE","vitis_design_icn_ctrl_2_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M02_AXI_tlm_MODE","vitis_design_icn_ctrl_2_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M03_AXI_tlm_MODE","vitis_design_icn_ctrl_3_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M03_AXI_tlm_MODE","vitis_design_icn_ctrl_3_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M04_AXI_tlm_MODE","vitis_design_icn_ctrl_4_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M04_AXI_tlm_MODE","vitis_design_icn_ctrl_4_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M05_AXI_tlm_MODE","vitis_design_icn_ctrl_5_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M05_AXI_tlm_MODE","vitis_design_icn_ctrl_5_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_2_0","M00_AXI_tlm_MODE","vitis_design_dummy_slave_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_2_0","M00_AXI_tlm_MODE","vitis_design_dummy_slave_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_3_0","M00_AXI_tlm_MODE","vitis_design_dummy_slave_1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_3_0","M00_AXI_tlm_MODE","vitis_design_dummy_slave_1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_4_0","M00_AXI_tlm_MODE","vitis_design_dummy_slave_2_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_4_0","M00_AXI_tlm_MODE","vitis_design_dummy_slave_2_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_5_0","M00_AXI_tlm_MODE","vitis_design_dummy_slave_3_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_5_0","M00_AXI_tlm_MODE","vitis_design_dummy_slave_3_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M10_AXI_tlm_MODE","vitis_design_dpa_hub_0","S_AXIMM_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M10_AXI_tlm_MODE","vitis_design_dpa_hub_0","S_AXIMM_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M09_AXI_tlm_MODE","vitis_design_dpa_ctrl_interconnect_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("vitis_design_icn_ctrl_1_0","M09_AXI_tlm_MODE","vitis_design_dpa_ctrl_interconnect_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("vitis_design_sci","ch0_lpddr4_c0_TLM_MODE",-1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("vitis_design_sci","ch0_lpddr4_c1_TLM_MODE",-1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("vitis_design_sci","ch1_lpddr4_c0_TLM_MODE",-1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("vitis_design_sci","ch1_lpddr4_c1_TLM_MODE",-1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("vitis_design_sci","ddr4_dimm1_sma_clk_TLM_MODE",-1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("vitis_design_sci","lpddr4_sma_clk1_TLM_MODE",-1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("vitis_design_sci","lpddr4_sma_clk2_TLM_MODE",-1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("vitis_design_sci","ddr4_dimm1_TLM_MODE",-1);
	
	xsc::utils::xsc_sim_manager::addInstance("vitis_design_sci", this);
	#if defined MTI_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM
	if(!xsc::utils::xsc_sim_manager::isMTlmWaveDatabaseInit()) {
	xsc::utils::xsc_sim_manager::setMTlmWaveDatabaseInit(true);
	scv_startup(); /* Initialize SCV: */
	scv_tr_wlf_init(); /* Tie databases to WLF: */
	scv_tr_db *txdb = new scv_tr_db("tlmWaveDB");
	if (txdb != NULL)
	  scv_tr_db::set_default_db(txdb);
	}
	#endif
	#if defined XM_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM
	if(!xsc::utils::xsc_sim_manager::isMTlmWaveDatabaseInit()){
	xsc::utils::xsc_sim_manager::setMTlmWaveDatabaseInit(true);
	cve_tr_sdi_init();
	scv_tr_db *txdb = new scv_tr_db("tlmWaveDB");
	if (txdb != NULL)
	  scv_tr_db::set_default_db(txdb);
	}
	#endif
}
vitis_design_sci::~vitis_design_sci()
{
}
void vitis_design_sci::initConnModule() {

}

void vitis_design_sci::before_end_of_elaboration() {
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_0=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_hub_0_sc*  inst_1=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_aximm_transaction_logger* log_inst_0 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_0");
	log_inst_0->setProxyRef(inst_0, inst_1, "vitis_design_dpa_ctrl_interconnect_0_M00_AXI_tlm", "vitis_design_dpa_hub_0_S_AXIFIFO_TLM", log_inst_0->m_transactionLogger);
	
	if(inst_0==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_1==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_0!=NULL && inst_1!=NULL) {
		inst_0->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_0->tar_rd_skt));
		log_inst_0->init_rd_skt->bind(*(inst_1->axilite_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_4=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_hub_0_sc*  inst_5=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	
	if(inst_4==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_5==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_4!=NULL && inst_5!=NULL) {
		inst_4->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_0->tar_wr_skt));
		log_inst_0->init_wr_skt->bind(*(inst_5->axilite_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_8=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_hub_0_sc*  inst_9=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_aximm_transaction_logger* log_inst_1 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_1");
	log_inst_1->setProxyRef(inst_8, inst_9, "vitis_design_dpa_ctrl_interconnect_0_M01_AXI_tlm", "vitis_design_dpa_hub_0_S_AXIHUB_TLM", log_inst_1->m_transactionLogger);
	
	if(inst_8==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_9==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_8!=NULL && inst_9!=NULL) {
		inst_8->M01_AXI_tlm_aximm_read_socket->bind(*(log_inst_1->tar_rd_skt));
		log_inst_1->init_rd_skt->bind(*(inst_9->s_axihub_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_12=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_hub_0_sc*  inst_13=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	
	if(inst_12==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_13==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_12!=NULL && inst_13!=NULL) {
		inst_12->M01_AXI_tlm_aximm_write_socket->bind(*(log_inst_1->tar_wr_skt));
		log_inst_1->init_wr_skt->bind(*(inst_13->s_axihub_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_16=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon0_0_sc*  inst_17=dynamic_cast<vitis_design_dpa_mon0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_0"));
	xtlm_aximm_transaction_logger* log_inst_2 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_2");
	log_inst_2->setProxyRef(inst_16, inst_17, "vitis_design_dpa_ctrl_interconnect_0_M02_AXI_tlm", "vitis_design_dpa_mon0_0_S_AXI_TLM", log_inst_2->m_transactionLogger);
	
	if(inst_16==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_17==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_0_sc"<<std::endl;
	}
	
	if (inst_16!=NULL && inst_17!=NULL) {
		inst_16->M02_AXI_tlm_aximm_read_socket->bind(*(log_inst_2->tar_rd_skt));
		log_inst_2->init_rd_skt->bind(*(inst_17->axilite_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_20=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon0_0_sc*  inst_21=dynamic_cast<vitis_design_dpa_mon0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_0"));
	
	if(inst_20==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_21==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_0_sc"<<std::endl;
	}
	
	if (inst_20!=NULL && inst_21!=NULL) {
		inst_20->M02_AXI_tlm_aximm_write_socket->bind(*(log_inst_2->tar_wr_skt));
		log_inst_2->init_wr_skt->bind(*(inst_21->axilite_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_24=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon1_0_sc*  inst_25=dynamic_cast<vitis_design_dpa_mon1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon1_0"));
	xtlm_aximm_transaction_logger* log_inst_3 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_3");
	log_inst_3->setProxyRef(inst_24, inst_25, "vitis_design_dpa_ctrl_interconnect_0_M03_AXI_tlm", "vitis_design_dpa_mon1_0_S_AXI_TLM", log_inst_3->m_transactionLogger);
	
	if(inst_24==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_25==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon1_0_sc"<<std::endl;
	}
	
	if (inst_24!=NULL && inst_25!=NULL) {
		inst_24->M03_AXI_tlm_aximm_read_socket->bind(*(log_inst_3->tar_rd_skt));
		log_inst_3->init_rd_skt->bind(*(inst_25->axilite_rd_skt));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_28=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon1_0_sc*  inst_29=dynamic_cast<vitis_design_dpa_mon1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon1_0"));
	
	if(inst_28==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_29==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon1_0_sc"<<std::endl;
	}
	
	if (inst_28!=NULL && inst_29!=NULL) {
		inst_28->M03_AXI_tlm_aximm_write_socket->bind(*(log_inst_3->tar_wr_skt));
		log_inst_3->init_wr_skt->bind(*(inst_29->axilite_wr_skt));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_32=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon2_0_sc*  inst_33=dynamic_cast<vitis_design_dpa_mon2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon2_0"));
	xtlm_aximm_transaction_logger* log_inst_4 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_4");
	log_inst_4->setProxyRef(inst_32, inst_33, "vitis_design_dpa_ctrl_interconnect_0_M04_AXI_tlm", "vitis_design_dpa_mon2_0_S_AXI_TLM", log_inst_4->m_transactionLogger);
	
	if(inst_32==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_33==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon2_0_sc"<<std::endl;
	}
	
	if (inst_32!=NULL && inst_33!=NULL) {
		inst_32->M04_AXI_tlm_aximm_read_socket->bind(*(log_inst_4->tar_rd_skt));
		log_inst_4->init_rd_skt->bind(*(inst_33->axilite_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_36=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon2_0_sc*  inst_37=dynamic_cast<vitis_design_dpa_mon2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon2_0"));
	
	if(inst_36==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_37==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon2_0_sc"<<std::endl;
	}
	
	if (inst_36!=NULL && inst_37!=NULL) {
		inst_36->M04_AXI_tlm_aximm_write_socket->bind(*(log_inst_4->tar_wr_skt));
		log_inst_4->init_wr_skt->bind(*(inst_37->axilite_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_40=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon3_0_sc*  inst_41=dynamic_cast<vitis_design_dpa_mon3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon3_0"));
	xtlm_aximm_transaction_logger* log_inst_5 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_5");
	log_inst_5->setProxyRef(inst_40, inst_41, "vitis_design_dpa_ctrl_interconnect_0_M05_AXI_tlm", "vitis_design_dpa_mon3_0_S_AXI_TLM", log_inst_5->m_transactionLogger);
	
	if(inst_40==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_41==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon3_0_sc"<<std::endl;
	}
	
	if (inst_40!=NULL && inst_41!=NULL) {
		inst_40->M05_AXI_tlm_aximm_read_socket->bind(*(log_inst_5->tar_rd_skt));
		log_inst_5->init_rd_skt->bind(*(inst_41->axilite_rd_skt));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_44=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon3_0_sc*  inst_45=dynamic_cast<vitis_design_dpa_mon3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon3_0"));
	
	if(inst_44==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_45==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon3_0_sc"<<std::endl;
	}
	
	if (inst_44!=NULL && inst_45!=NULL) {
		inst_44->M05_AXI_tlm_aximm_write_socket->bind(*(log_inst_5->tar_wr_skt));
		log_inst_5->init_wr_skt->bind(*(inst_45->axilite_wr_skt));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_48=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon4_0_sc*  inst_49=dynamic_cast<vitis_design_dpa_mon4_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon4_0"));
	xtlm_aximm_transaction_logger* log_inst_6 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_6");
	log_inst_6->setProxyRef(inst_48, inst_49, "vitis_design_dpa_ctrl_interconnect_0_M06_AXI_tlm", "vitis_design_dpa_mon4_0_S_AXI_TLM", log_inst_6->m_transactionLogger);
	
	if(inst_48==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_49==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon4_0_sc"<<std::endl;
	}
	
	if (inst_48!=NULL && inst_49!=NULL) {
		inst_48->M06_AXI_tlm_aximm_read_socket->bind(*(log_inst_6->tar_rd_skt));
		log_inst_6->init_rd_skt->bind(*(inst_49->axilite_rd_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_52=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon4_0_sc*  inst_53=dynamic_cast<vitis_design_dpa_mon4_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon4_0"));
	
	if(inst_52==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_53==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon4_0_sc"<<std::endl;
	}
	
	if (inst_52!=NULL && inst_53!=NULL) {
		inst_52->M06_AXI_tlm_aximm_write_socket->bind(*(log_inst_6->tar_wr_skt));
		log_inst_6->init_wr_skt->bind(*(inst_53->axilite_wr_socket));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_56=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon5_0_sc*  inst_57=dynamic_cast<vitis_design_dpa_mon5_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon5_0"));
	xtlm_aximm_transaction_logger* log_inst_7 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_7");
	log_inst_7->setProxyRef(inst_56, inst_57, "vitis_design_dpa_ctrl_interconnect_0_M07_AXI_tlm", "vitis_design_dpa_mon5_0_S_AXI_TLM", log_inst_7->m_transactionLogger);
	
	if(inst_56==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_57==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon5_0_sc"<<std::endl;
	}
	
	if (inst_56!=NULL && inst_57!=NULL) {
		inst_56->M07_AXI_tlm_aximm_read_socket->bind(*(log_inst_7->tar_rd_skt));
		log_inst_7->init_rd_skt->bind(*(inst_57->axilite_rd_skt));
	}
	
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_60=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	vitis_design_dpa_mon5_0_sc*  inst_61=dynamic_cast<vitis_design_dpa_mon5_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon5_0"));
	
	if(inst_60==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	if(inst_61==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon5_0_sc"<<std::endl;
	}
	
	if (inst_60!=NULL && inst_61!=NULL) {
		inst_60->M07_AXI_tlm_aximm_write_socket->bind(*(log_inst_7->tar_wr_skt));
		log_inst_7->init_wr_skt->bind(*(inst_61->axilite_wr_skt));
	}
	
	vitis_design_dpa_mon0_0_sc*  inst_64=dynamic_cast<vitis_design_dpa_mon0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_0"));
	vitis_design_dpa_hub_0_sc*  inst_65=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_8 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_8");
	log_inst_8->setProxyRef(inst_64, inst_65, "vitis_design_dpa_mon0_0_TRACE_OUT_0_TLM", "vitis_design_dpa_hub_0_TRACE_IN_0_TLM", log_inst_8->m_transactionLogger);
	
	if(inst_64==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_0_sc"<<std::endl;
	}
	if(inst_65==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_64!=NULL && inst_65!=NULL) {
		inst_64->wr_trace_socket->bind(*(log_inst_8->tar_skt));
		log_inst_8->init_skt->bind(*(inst_65->trace_socket0));
	}
	
	vitis_design_dpa_mon0_0_sc*  inst_68=dynamic_cast<vitis_design_dpa_mon0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon0_0"));
	vitis_design_dpa_hub_0_sc*  inst_69=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_9 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_9");
	log_inst_9->setProxyRef(inst_68, inst_69, "vitis_design_dpa_mon0_0_TRACE_OUT_1_TLM", "vitis_design_dpa_hub_0_TRACE_IN_1_TLM", log_inst_9->m_transactionLogger);
	
	if(inst_68==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon0_0_sc"<<std::endl;
	}
	if(inst_69==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_68!=NULL && inst_69!=NULL) {
		inst_68->rd_trace_socket->bind(*(log_inst_9->tar_skt));
		log_inst_9->init_skt->bind(*(inst_69->trace_socket1));
	}
	
	vitis_design_dpa_mon1_0_sc*  inst_72=dynamic_cast<vitis_design_dpa_mon1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon1_0"));
	vitis_design_dpa_hub_0_sc*  inst_73=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_10 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_10");
	log_inst_10->setProxyRef(inst_72, inst_73, "vitis_design_dpa_mon1_0_TRACE_OUT_TLM", "vitis_design_dpa_hub_0_TRACE_IN_2_TLM", log_inst_10->m_transactionLogger);
	
	if(inst_72==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon1_0_sc"<<std::endl;
	}
	if(inst_73==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_72!=NULL && inst_73!=NULL) {
		inst_72->trace_skt->bind(*(log_inst_10->tar_skt));
		log_inst_10->init_skt->bind(*(inst_73->trace_socket2));
	}
	
	vitis_design_dpa_mon2_0_sc*  inst_76=dynamic_cast<vitis_design_dpa_mon2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon2_0"));
	vitis_design_dpa_hub_0_sc*  inst_77=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_11 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_11");
	log_inst_11->setProxyRef(inst_76, inst_77, "vitis_design_dpa_mon2_0_TRACE_OUT_0_TLM", "vitis_design_dpa_hub_0_TRACE_IN_3_TLM", log_inst_11->m_transactionLogger);
	
	if(inst_76==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon2_0_sc"<<std::endl;
	}
	if(inst_77==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_76!=NULL && inst_77!=NULL) {
		inst_76->wr_trace_socket->bind(*(log_inst_11->tar_skt));
		log_inst_11->init_skt->bind(*(inst_77->trace_socket3));
	}
	
	vitis_design_dpa_mon2_0_sc*  inst_80=dynamic_cast<vitis_design_dpa_mon2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon2_0"));
	vitis_design_dpa_hub_0_sc*  inst_81=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_12 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_12");
	log_inst_12->setProxyRef(inst_80, inst_81, "vitis_design_dpa_mon2_0_TRACE_OUT_1_TLM", "vitis_design_dpa_hub_0_TRACE_IN_4_TLM", log_inst_12->m_transactionLogger);
	
	if(inst_80==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon2_0_sc"<<std::endl;
	}
	if(inst_81==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_80!=NULL && inst_81!=NULL) {
		inst_80->rd_trace_socket->bind(*(log_inst_12->tar_skt));
		log_inst_12->init_skt->bind(*(inst_81->trace_socket4));
	}
	
	vitis_design_dpa_mon3_0_sc*  inst_84=dynamic_cast<vitis_design_dpa_mon3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon3_0"));
	vitis_design_dpa_hub_0_sc*  inst_85=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_13 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_13");
	log_inst_13->setProxyRef(inst_84, inst_85, "vitis_design_dpa_mon3_0_TRACE_OUT_TLM", "vitis_design_dpa_hub_0_TRACE_IN_5_TLM", log_inst_13->m_transactionLogger);
	
	if(inst_84==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon3_0_sc"<<std::endl;
	}
	if(inst_85==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_84!=NULL && inst_85!=NULL) {
		inst_84->trace_skt->bind(*(log_inst_13->tar_skt));
		log_inst_13->init_skt->bind(*(inst_85->trace_socket5));
	}
	
	vitis_design_dpa_mon4_0_sc*  inst_88=dynamic_cast<vitis_design_dpa_mon4_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon4_0"));
	vitis_design_dpa_hub_0_sc*  inst_89=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_14 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_14");
	log_inst_14->setProxyRef(inst_88, inst_89, "vitis_design_dpa_mon4_0_TRACE_OUT_0_TLM", "vitis_design_dpa_hub_0_TRACE_IN_6_TLM", log_inst_14->m_transactionLogger);
	
	if(inst_88==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon4_0_sc"<<std::endl;
	}
	if(inst_89==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_88!=NULL && inst_89!=NULL) {
		inst_88->wr_trace_socket->bind(*(log_inst_14->tar_skt));
		log_inst_14->init_skt->bind(*(inst_89->trace_socket6));
	}
	
	vitis_design_dpa_mon4_0_sc*  inst_92=dynamic_cast<vitis_design_dpa_mon4_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon4_0"));
	vitis_design_dpa_hub_0_sc*  inst_93=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_15 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_15");
	log_inst_15->setProxyRef(inst_92, inst_93, "vitis_design_dpa_mon4_0_TRACE_OUT_1_TLM", "vitis_design_dpa_hub_0_TRACE_IN_7_TLM", log_inst_15->m_transactionLogger);
	
	if(inst_92==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon4_0_sc"<<std::endl;
	}
	if(inst_93==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_92!=NULL && inst_93!=NULL) {
		inst_92->rd_trace_socket->bind(*(log_inst_15->tar_skt));
		log_inst_15->init_skt->bind(*(inst_93->trace_socket7));
	}
	
	vitis_design_dpa_mon5_0_sc*  inst_96=dynamic_cast<vitis_design_dpa_mon5_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_mon5_0"));
	vitis_design_dpa_hub_0_sc*  inst_97=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_16 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_16");
	log_inst_16->setProxyRef(inst_96, inst_97, "vitis_design_dpa_mon5_0_TRACE_OUT_TLM", "vitis_design_dpa_hub_0_TRACE_IN_8_TLM", log_inst_16->m_transactionLogger);
	
	if(inst_96==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_mon5_0_sc"<<std::endl;
	}
	if(inst_97==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_96!=NULL && inst_97!=NULL) {
		inst_96->trace_skt->bind(*(log_inst_16->tar_skt));
		log_inst_16->init_skt->bind(*(inst_97->trace_socket8));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_100=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_101=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	xtlm_aximm_transaction_logger* log_inst_17 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_17");
	log_inst_17->setProxyRef(inst_100, inst_101, "vitis_design_CIPS_0_0_PMC_NOC_AXI_0_tlm", "vitis_design_cips_noc_0_S07_AXI_tlm", log_inst_17->m_transactionLogger);
	
	if(inst_100==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_101==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_100!=NULL && inst_101!=NULL) {
		inst_100->PMC_NOC_AXI_0_tlm_aximm_read_socket->bind(*(log_inst_17->tar_rd_skt));
		log_inst_17->init_rd_skt->bind(*(inst_101->S07_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_104=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_105=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	
	if(inst_104==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_105==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_104!=NULL && inst_105!=NULL) {
		inst_104->PMC_NOC_AXI_0_tlm_aximm_write_socket->bind(*(log_inst_17->tar_wr_skt));
		log_inst_17->init_wr_skt->bind(*(inst_105->S07_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_108=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_109=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	xtlm_aximm_transaction_logger* log_inst_18 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_18");
	log_inst_18->setProxyRef(inst_108, inst_109, "vitis_design_CIPS_0_0_FPD_CCI_NOC_0_tlm", "vitis_design_cips_noc_0_S00_AXI_tlm", log_inst_18->m_transactionLogger);
	
	if(inst_108==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_109==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_108!=NULL && inst_109!=NULL) {
		inst_108->FPD_CCI_NOC_0_tlm_aximm_read_socket->bind(*(log_inst_18->tar_rd_skt));
		log_inst_18->init_rd_skt->bind(*(inst_109->S00_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_112=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_113=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	
	if(inst_112==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_113==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_112!=NULL && inst_113!=NULL) {
		inst_112->FPD_CCI_NOC_0_tlm_aximm_write_socket->bind(*(log_inst_18->tar_wr_skt));
		log_inst_18->init_wr_skt->bind(*(inst_113->S00_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_116=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_117=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	xtlm_aximm_transaction_logger* log_inst_19 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_19");
	log_inst_19->setProxyRef(inst_116, inst_117, "vitis_design_CIPS_0_0_FPD_CCI_NOC_1_tlm", "vitis_design_cips_noc_0_S01_AXI_tlm", log_inst_19->m_transactionLogger);
	
	if(inst_116==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_117==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_116!=NULL && inst_117!=NULL) {
		inst_116->FPD_CCI_NOC_1_tlm_aximm_read_socket->bind(*(log_inst_19->tar_rd_skt));
		log_inst_19->init_rd_skt->bind(*(inst_117->S01_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_120=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_121=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	
	if(inst_120==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_121==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_120!=NULL && inst_121!=NULL) {
		inst_120->FPD_CCI_NOC_1_tlm_aximm_write_socket->bind(*(log_inst_19->tar_wr_skt));
		log_inst_19->init_wr_skt->bind(*(inst_121->S01_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_124=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_125=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	xtlm_aximm_transaction_logger* log_inst_20 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_20");
	log_inst_20->setProxyRef(inst_124, inst_125, "vitis_design_CIPS_0_0_FPD_CCI_NOC_2_tlm", "vitis_design_cips_noc_0_S02_AXI_tlm", log_inst_20->m_transactionLogger);
	
	if(inst_124==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_125==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_124!=NULL && inst_125!=NULL) {
		inst_124->FPD_CCI_NOC_2_tlm_aximm_read_socket->bind(*(log_inst_20->tar_rd_skt));
		log_inst_20->init_rd_skt->bind(*(inst_125->S02_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_128=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_129=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	
	if(inst_128==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_129==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_128!=NULL && inst_129!=NULL) {
		inst_128->FPD_CCI_NOC_2_tlm_aximm_write_socket->bind(*(log_inst_20->tar_wr_skt));
		log_inst_20->init_wr_skt->bind(*(inst_129->S02_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_132=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_133=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	xtlm_aximm_transaction_logger* log_inst_21 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_21");
	log_inst_21->setProxyRef(inst_132, inst_133, "vitis_design_CIPS_0_0_FPD_CCI_NOC_3_tlm", "vitis_design_cips_noc_0_S03_AXI_tlm", log_inst_21->m_transactionLogger);
	
	if(inst_132==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_133==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_132!=NULL && inst_133!=NULL) {
		inst_132->FPD_CCI_NOC_3_tlm_aximm_read_socket->bind(*(log_inst_21->tar_rd_skt));
		log_inst_21->init_rd_skt->bind(*(inst_133->S03_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_136=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_137=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	
	if(inst_136==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_137==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_136!=NULL && inst_137!=NULL) {
		inst_136->FPD_CCI_NOC_3_tlm_aximm_write_socket->bind(*(log_inst_21->tar_wr_skt));
		log_inst_21->init_wr_skt->bind(*(inst_137->S03_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_140=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_141=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	xtlm_aximm_transaction_logger* log_inst_22 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_22");
	log_inst_22->setProxyRef(inst_140, inst_141, "vitis_design_CIPS_0_0_FPD_AXI_NOC_0_tlm", "vitis_design_cips_noc_0_S04_AXI_tlm", log_inst_22->m_transactionLogger);
	
	if(inst_140==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_141==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_140!=NULL && inst_141!=NULL) {
		inst_140->FPD_AXI_NOC_0_tlm_aximm_read_socket->bind(*(log_inst_22->tar_rd_skt));
		log_inst_22->init_rd_skt->bind(*(inst_141->S04_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_144=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_145=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	
	if(inst_144==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_145==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_144!=NULL && inst_145!=NULL) {
		inst_144->FPD_AXI_NOC_0_tlm_aximm_write_socket->bind(*(log_inst_22->tar_wr_skt));
		log_inst_22->init_wr_skt->bind(*(inst_145->S04_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_148=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_149=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	xtlm_aximm_transaction_logger* log_inst_23 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_23");
	log_inst_23->setProxyRef(inst_148, inst_149, "vitis_design_CIPS_0_0_FPD_AXI_NOC_1_tlm", "vitis_design_cips_noc_0_S05_AXI_tlm", log_inst_23->m_transactionLogger);
	
	if(inst_148==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_149==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_148!=NULL && inst_149!=NULL) {
		inst_148->FPD_AXI_NOC_1_tlm_aximm_read_socket->bind(*(log_inst_23->tar_rd_skt));
		log_inst_23->init_rd_skt->bind(*(inst_149->S05_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_152=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_153=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	
	if(inst_152==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_153==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_152!=NULL && inst_153!=NULL) {
		inst_152->FPD_AXI_NOC_1_tlm_aximm_write_socket->bind(*(log_inst_23->tar_wr_skt));
		log_inst_23->init_wr_skt->bind(*(inst_153->S05_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_156=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_157=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	xtlm_aximm_transaction_logger* log_inst_24 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_24");
	log_inst_24->setProxyRef(inst_156, inst_157, "vitis_design_CIPS_0_0_LPD_AXI_NOC_0_tlm", "vitis_design_cips_noc_0_S06_AXI_tlm", log_inst_24->m_transactionLogger);
	
	if(inst_156==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_157==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_156!=NULL && inst_157!=NULL) {
		inst_156->LPD_AXI_NOC_0_tlm_aximm_read_socket->bind(*(log_inst_24->tar_rd_skt));
		log_inst_24->init_rd_skt->bind(*(inst_157->S06_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_160=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_cips_noc_0_sc*  inst_161=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	
	if(inst_160==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_161==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	
	if (inst_160!=NULL && inst_161!=NULL) {
		inst_160->LPD_AXI_NOC_0_tlm_aximm_write_socket->bind(*(log_inst_24->tar_wr_skt));
		log_inst_24->init_wr_skt->bind(*(inst_161->S06_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_164=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_icn_ctrl_1_0_sc*  inst_165=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	xtlm_aximm_transaction_logger* log_inst_25 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_25");
	log_inst_25->setProxyRef(inst_164, inst_165, "vitis_design_CIPS_0_0_M_AXI_FPD_tlm", "vitis_design_icn_ctrl_1_0_S00_AXI_tlm", log_inst_25->m_transactionLogger);
	
	if(inst_164==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_165==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	
	if (inst_164!=NULL && inst_165!=NULL) {
		inst_164->M_AXI_FPD_tlm_aximm_read_socket->bind(*(log_inst_25->tar_rd_skt));
		log_inst_25->init_rd_skt->bind(*(inst_165->S00_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_CIPS_0_0_sc*  inst_168=dynamic_cast<vitis_design_CIPS_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_CIPS_0_0"));
	vitis_design_icn_ctrl_1_0_sc*  inst_169=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	
	if(inst_168==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_CIPS_0_0_sc"<<std::endl;
	}
	if(inst_169==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	
	if (inst_168!=NULL && inst_169!=NULL) {
		inst_168->M_AXI_FPD_tlm_aximm_write_socket->bind(*(log_inst_25->tar_wr_skt));
		log_inst_25->init_wr_skt->bind(*(inst_169->S00_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_cips_noc_0_sc*  inst_172=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	vitis_design_ai_engine_0_0_sc*  inst_173=dynamic_cast<vitis_design_ai_engine_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_ai_engine_0_0"));
	xtlm_aximm_transaction_logger* log_inst_26 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_26");
	log_inst_26->setProxyRef(inst_172, inst_173, "vitis_design_cips_noc_0_M00_AXI_tlm", "vitis_design_ai_engine_0_0_S00_AXI_tlm", log_inst_26->m_transactionLogger);
	
	if(inst_172==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	if(inst_173==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_ai_engine_0_0_sc"<<std::endl;
	}
	
	if (inst_172!=NULL && inst_173!=NULL) {
		inst_172->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_26->tar_rd_skt));
		log_inst_26->init_rd_skt->bind(*(inst_173->S00_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_cips_noc_0_sc*  inst_176=dynamic_cast<vitis_design_cips_noc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_cips_noc_0"));
	vitis_design_ai_engine_0_0_sc*  inst_177=dynamic_cast<vitis_design_ai_engine_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_ai_engine_0_0"));
	
	if(inst_176==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_cips_noc_0_sc"<<std::endl;
	}
	if(inst_177==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_ai_engine_0_0_sc"<<std::endl;
	}
	
	if (inst_176!=NULL && inst_177!=NULL) {
		inst_176->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_26->tar_wr_skt));
		log_inst_26->init_wr_skt->bind(*(inst_177->S00_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_180=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_icn_ctrl_2_0_sc*  inst_181=dynamic_cast<vitis_design_icn_ctrl_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_2_0"));
	xtlm_aximm_transaction_logger* log_inst_27 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_27");
	log_inst_27->setProxyRef(inst_180, inst_181, "vitis_design_icn_ctrl_1_0_M02_AXI_tlm", "vitis_design_icn_ctrl_2_0_S00_AXI_tlm", log_inst_27->m_transactionLogger);
	
	if(inst_180==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_181==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_2_0_sc"<<std::endl;
	}
	
	if (inst_180!=NULL && inst_181!=NULL) {
		inst_180->M02_AXI_tlm_aximm_read_socket->bind(*(log_inst_27->tar_rd_skt));
		log_inst_27->init_rd_skt->bind(*(inst_181->S00_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_184=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_icn_ctrl_2_0_sc*  inst_185=dynamic_cast<vitis_design_icn_ctrl_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_2_0"));
	
	if(inst_184==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_185==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_2_0_sc"<<std::endl;
	}
	
	if (inst_184!=NULL && inst_185!=NULL) {
		inst_184->M02_AXI_tlm_aximm_write_socket->bind(*(log_inst_27->tar_wr_skt));
		log_inst_27->init_wr_skt->bind(*(inst_185->S00_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_188=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_icn_ctrl_3_0_sc*  inst_189=dynamic_cast<vitis_design_icn_ctrl_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_3_0"));
	xtlm_aximm_transaction_logger* log_inst_28 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_28");
	log_inst_28->setProxyRef(inst_188, inst_189, "vitis_design_icn_ctrl_1_0_M03_AXI_tlm", "vitis_design_icn_ctrl_3_0_S00_AXI_tlm", log_inst_28->m_transactionLogger);
	
	if(inst_188==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_189==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_3_0_sc"<<std::endl;
	}
	
	if (inst_188!=NULL && inst_189!=NULL) {
		inst_188->M03_AXI_tlm_aximm_read_socket->bind(*(log_inst_28->tar_rd_skt));
		log_inst_28->init_rd_skt->bind(*(inst_189->S00_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_192=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_icn_ctrl_3_0_sc*  inst_193=dynamic_cast<vitis_design_icn_ctrl_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_3_0"));
	
	if(inst_192==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_193==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_3_0_sc"<<std::endl;
	}
	
	if (inst_192!=NULL && inst_193!=NULL) {
		inst_192->M03_AXI_tlm_aximm_write_socket->bind(*(log_inst_28->tar_wr_skt));
		log_inst_28->init_wr_skt->bind(*(inst_193->S00_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_196=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_icn_ctrl_4_0_sc*  inst_197=dynamic_cast<vitis_design_icn_ctrl_4_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_4_0"));
	xtlm_aximm_transaction_logger* log_inst_29 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_29");
	log_inst_29->setProxyRef(inst_196, inst_197, "vitis_design_icn_ctrl_1_0_M04_AXI_tlm", "vitis_design_icn_ctrl_4_0_S00_AXI_tlm", log_inst_29->m_transactionLogger);
	
	if(inst_196==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_197==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_4_0_sc"<<std::endl;
	}
	
	if (inst_196!=NULL && inst_197!=NULL) {
		inst_196->M04_AXI_tlm_aximm_read_socket->bind(*(log_inst_29->tar_rd_skt));
		log_inst_29->init_rd_skt->bind(*(inst_197->S00_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_200=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_icn_ctrl_4_0_sc*  inst_201=dynamic_cast<vitis_design_icn_ctrl_4_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_4_0"));
	
	if(inst_200==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_201==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_4_0_sc"<<std::endl;
	}
	
	if (inst_200!=NULL && inst_201!=NULL) {
		inst_200->M04_AXI_tlm_aximm_write_socket->bind(*(log_inst_29->tar_wr_skt));
		log_inst_29->init_wr_skt->bind(*(inst_201->S00_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_204=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_icn_ctrl_5_0_sc*  inst_205=dynamic_cast<vitis_design_icn_ctrl_5_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_5_0"));
	xtlm_aximm_transaction_logger* log_inst_30 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_30");
	log_inst_30->setProxyRef(inst_204, inst_205, "vitis_design_icn_ctrl_1_0_M05_AXI_tlm", "vitis_design_icn_ctrl_5_0_S00_AXI_tlm", log_inst_30->m_transactionLogger);
	
	if(inst_204==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_205==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_5_0_sc"<<std::endl;
	}
	
	if (inst_204!=NULL && inst_205!=NULL) {
		inst_204->M05_AXI_tlm_aximm_read_socket->bind(*(log_inst_30->tar_rd_skt));
		log_inst_30->init_rd_skt->bind(*(inst_205->S00_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_208=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_icn_ctrl_5_0_sc*  inst_209=dynamic_cast<vitis_design_icn_ctrl_5_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_5_0"));
	
	if(inst_208==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_209==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_5_0_sc"<<std::endl;
	}
	
	if (inst_208!=NULL && inst_209!=NULL) {
		inst_208->M05_AXI_tlm_aximm_write_socket->bind(*(log_inst_30->tar_wr_skt));
		log_inst_30->init_wr_skt->bind(*(inst_209->S00_AXI_tlm_aximm_write_socket));
	}
	
	vitis_design_icn_ctrl_2_0_sc*  inst_212=dynamic_cast<vitis_design_icn_ctrl_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_2_0"));
	vitis_design_dummy_slave_0_0_sc*  inst_213=dynamic_cast<vitis_design_dummy_slave_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dummy_slave_0_0"));
	xtlm_aximm_transaction_logger* log_inst_31 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_31");
	log_inst_31->setProxyRef(inst_212, inst_213, "vitis_design_icn_ctrl_2_0_M00_AXI_tlm", "vitis_design_dummy_slave_0_0_S_AXI_TLM", log_inst_31->m_transactionLogger);
	
	if(inst_212==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_2_0_sc"<<std::endl;
	}
	if(inst_213==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dummy_slave_0_0_sc"<<std::endl;
	}
	
	if (inst_212!=NULL && inst_213!=NULL) {
		inst_212->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_31->tar_rd_skt));
		log_inst_31->init_rd_skt->bind(*(inst_213->S_TARGET_rd_socket));
	}
	
	vitis_design_icn_ctrl_2_0_sc*  inst_216=dynamic_cast<vitis_design_icn_ctrl_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_2_0"));
	vitis_design_dummy_slave_0_0_sc*  inst_217=dynamic_cast<vitis_design_dummy_slave_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dummy_slave_0_0"));
	
	if(inst_216==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_2_0_sc"<<std::endl;
	}
	if(inst_217==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dummy_slave_0_0_sc"<<std::endl;
	}
	
	if (inst_216!=NULL && inst_217!=NULL) {
		inst_216->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_31->tar_wr_skt));
		log_inst_31->init_wr_skt->bind(*(inst_217->S_TARGET_wr_socket));
	}
	
	vitis_design_icn_ctrl_3_0_sc*  inst_220=dynamic_cast<vitis_design_icn_ctrl_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_3_0"));
	vitis_design_dummy_slave_1_0_sc*  inst_221=dynamic_cast<vitis_design_dummy_slave_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dummy_slave_1_0"));
	xtlm_aximm_transaction_logger* log_inst_32 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_32");
	log_inst_32->setProxyRef(inst_220, inst_221, "vitis_design_icn_ctrl_3_0_M00_AXI_tlm", "vitis_design_dummy_slave_1_0_S_AXI_TLM", log_inst_32->m_transactionLogger);
	
	if(inst_220==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_3_0_sc"<<std::endl;
	}
	if(inst_221==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dummy_slave_1_0_sc"<<std::endl;
	}
	
	if (inst_220!=NULL && inst_221!=NULL) {
		inst_220->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_32->tar_rd_skt));
		log_inst_32->init_rd_skt->bind(*(inst_221->S_TARGET_rd_socket));
	}
	
	vitis_design_icn_ctrl_3_0_sc*  inst_224=dynamic_cast<vitis_design_icn_ctrl_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_3_0"));
	vitis_design_dummy_slave_1_0_sc*  inst_225=dynamic_cast<vitis_design_dummy_slave_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dummy_slave_1_0"));
	
	if(inst_224==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_3_0_sc"<<std::endl;
	}
	if(inst_225==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dummy_slave_1_0_sc"<<std::endl;
	}
	
	if (inst_224!=NULL && inst_225!=NULL) {
		inst_224->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_32->tar_wr_skt));
		log_inst_32->init_wr_skt->bind(*(inst_225->S_TARGET_wr_socket));
	}
	
	vitis_design_icn_ctrl_4_0_sc*  inst_228=dynamic_cast<vitis_design_icn_ctrl_4_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_4_0"));
	vitis_design_dummy_slave_2_0_sc*  inst_229=dynamic_cast<vitis_design_dummy_slave_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dummy_slave_2_0"));
	xtlm_aximm_transaction_logger* log_inst_33 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_33");
	log_inst_33->setProxyRef(inst_228, inst_229, "vitis_design_icn_ctrl_4_0_M00_AXI_tlm", "vitis_design_dummy_slave_2_0_S_AXI_TLM", log_inst_33->m_transactionLogger);
	
	if(inst_228==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_4_0_sc"<<std::endl;
	}
	if(inst_229==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dummy_slave_2_0_sc"<<std::endl;
	}
	
	if (inst_228!=NULL && inst_229!=NULL) {
		inst_228->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_33->tar_rd_skt));
		log_inst_33->init_rd_skt->bind(*(inst_229->S_TARGET_rd_socket));
	}
	
	vitis_design_icn_ctrl_4_0_sc*  inst_232=dynamic_cast<vitis_design_icn_ctrl_4_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_4_0"));
	vitis_design_dummy_slave_2_0_sc*  inst_233=dynamic_cast<vitis_design_dummy_slave_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dummy_slave_2_0"));
	
	if(inst_232==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_4_0_sc"<<std::endl;
	}
	if(inst_233==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dummy_slave_2_0_sc"<<std::endl;
	}
	
	if (inst_232!=NULL && inst_233!=NULL) {
		inst_232->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_33->tar_wr_skt));
		log_inst_33->init_wr_skt->bind(*(inst_233->S_TARGET_wr_socket));
	}
	
	vitis_design_icn_ctrl_5_0_sc*  inst_236=dynamic_cast<vitis_design_icn_ctrl_5_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_5_0"));
	vitis_design_dummy_slave_3_0_sc*  inst_237=dynamic_cast<vitis_design_dummy_slave_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dummy_slave_3_0"));
	xtlm_aximm_transaction_logger* log_inst_34 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_34");
	log_inst_34->setProxyRef(inst_236, inst_237, "vitis_design_icn_ctrl_5_0_M00_AXI_tlm", "vitis_design_dummy_slave_3_0_S_AXI_TLM", log_inst_34->m_transactionLogger);
	
	if(inst_236==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_5_0_sc"<<std::endl;
	}
	if(inst_237==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dummy_slave_3_0_sc"<<std::endl;
	}
	
	if (inst_236!=NULL && inst_237!=NULL) {
		inst_236->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_34->tar_rd_skt));
		log_inst_34->init_rd_skt->bind(*(inst_237->S_TARGET_rd_socket));
	}
	
	vitis_design_icn_ctrl_5_0_sc*  inst_240=dynamic_cast<vitis_design_icn_ctrl_5_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_5_0"));
	vitis_design_dummy_slave_3_0_sc*  inst_241=dynamic_cast<vitis_design_dummy_slave_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dummy_slave_3_0"));
	
	if(inst_240==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_5_0_sc"<<std::endl;
	}
	if(inst_241==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dummy_slave_3_0_sc"<<std::endl;
	}
	
	if (inst_240!=NULL && inst_241!=NULL) {
		inst_240->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_34->tar_wr_skt));
		log_inst_34->init_wr_skt->bind(*(inst_241->S_TARGET_wr_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_244=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_dpa_hub_0_sc*  inst_245=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	xtlm_aximm_transaction_logger* log_inst_35 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_35");
	log_inst_35->setProxyRef(inst_244, inst_245, "vitis_design_icn_ctrl_1_0_M10_AXI_tlm", "vitis_design_dpa_hub_0_S_AXIMM_TLM", log_inst_35->m_transactionLogger);
	
	if(inst_244==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_245==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_244!=NULL && inst_245!=NULL) {
		inst_244->M10_AXI_tlm_aximm_read_socket->bind(*(log_inst_35->tar_rd_skt));
		log_inst_35->init_rd_skt->bind(*(inst_245->s_aximm_rd_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_248=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_dpa_hub_0_sc*  inst_249=dynamic_cast<vitis_design_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_hub_0"));
	
	if(inst_248==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_249==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_248!=NULL && inst_249!=NULL) {
		inst_248->M10_AXI_tlm_aximm_write_socket->bind(*(log_inst_35->tar_wr_skt));
		log_inst_35->init_wr_skt->bind(*(inst_249->s_aximm_wr_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_252=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_253=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	xtlm_aximm_transaction_logger* log_inst_36 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_36");
	log_inst_36->setProxyRef(inst_252, inst_253, "vitis_design_icn_ctrl_1_0_M09_AXI_tlm", "vitis_design_dpa_ctrl_interconnect_0_S00_AXI_tlm", log_inst_36->m_transactionLogger);
	
	if(inst_252==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_253==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	
	if (inst_252!=NULL && inst_253!=NULL) {
		inst_252->M09_AXI_tlm_aximm_read_socket->bind(*(log_inst_36->tar_rd_skt));
		log_inst_36->init_rd_skt->bind(*(inst_253->S00_AXI_tlm_aximm_read_socket));
	}
	
	vitis_design_icn_ctrl_1_0_sc*  inst_256=dynamic_cast<vitis_design_icn_ctrl_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_icn_ctrl_1_0"));
	vitis_design_dpa_ctrl_interconnect_0_sc*  inst_257=dynamic_cast<vitis_design_dpa_ctrl_interconnect_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("vitis_design_dpa_ctrl_interconnect_0"));
	
	if(inst_256==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_icn_ctrl_1_0_sc"<<std::endl;
	}
	if(inst_257==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind vitis_design_dpa_ctrl_interconnect_0_sc"<<std::endl;
	}
	
	if (inst_256!=NULL && inst_257!=NULL) {
		inst_256->M09_AXI_tlm_aximm_write_socket->bind(*(log_inst_36->tar_wr_skt));
		log_inst_36->init_wr_skt->bind(*(inst_257->S00_AXI_tlm_aximm_write_socket));
	}
	
}
#ifdef MTI_SYSTEMC
SC_MODULE_EXPORT(vitis_design_sci);
#endif

#ifdef XM_SYSTEMC
XMSC_MODULE_EXPORT(vitis_design_sci);
#endif

#ifdef RIVIERA
SC_MODULE_EXPORT(vitis_design_sci);
#endif

