//File Automatically generated by SystemC Netlister Time
#include "bd_28ba_sci.h"
#include "bd_28ba_sci.h"
bd_28ba_sci::bd_28ba_sci(sc_core::sc_module_name name):sc_module(name) {
//Exported sockets Instantiation
xsc::utils::xsc_sim_manager::addInstance("bd_28ba_sci", this);
}
bd_28ba_sci::~bd_28ba_sci() {
}
